common/errors/errors.go, main/run.go
修正main包反射后包路径为main,不需要修剪的问题.
这个问题导致在启动时,如有无法读取证书等错误,会出现
%!s(PANIC=Error method: runtime error: slice bounds out of range [26:4])
=> fix trim package name error

main/jsonem/jsonem.go, main/run.go
=> Config: handle errors correctly 

go.mod, go.sum, infra/conf/serial/loader.go
目前 [github.com/BurntSushi/toml](https://github.com/BurntSushi/toml) 已经停止维护，且不支持新的 TOML 标准。  
改换为 [github.com/pelletier/go-toml](https://github.com/pelletier/go-toml)
=> Change TOML package to github.com/pelletier/go-toml

proxy/trojan/protocol.go, proxy/trojan/protocol_test.go, proxy/trojan/server.go
既然buf.Buffer里面已经带了UDPDestination，可以精简掉一些不必要的代码
=> 精简trojan udp的处理代码

app/dns/dohdns.go
1. fixed XTLS#104
因为 'Dispatched connection will be closed (interrupted) after each request'.
所以原来的远程DOH方式在高并发时,第一个DNS请求返回后连接关闭,后续使用同一个连接的请求失败.出现'app/dns: failed to retrieve response > Post "https://1.0.0.1/dns-query": io: read/write on closed pipe'的错误.
这个修改仅针对 non-local DOH(即远程DOH).
**其余模式(如local DOH)行为和以前一致.**
2. apply routing for non-local DoH requests
在很久前 v2ray 的一次 commit 中,将 non-local DoH 修改成直接使用第一个outbound, 而不经过路由. 
本意是为了防止某些不当配置时,陷入DNS解析的死循环,但这是很不合理的,会导致远程DOH请求发往的都是第一个 outbound 进行解析,得到的未必是最合适IP,甚至可能并未发往代理(比如第一个outbound为freedom时)
这个修改使远程DoH 请求和其他DNS(如最常用UDP模式)请求一样, 目标DNS服务器会经过路由模块分流,并且选择你期望的outbound
即可以同样通过类似
```
{
"type": "field",
"domain": [
"dns.google"
],
"outboundTag": "proxy"
},
{
"type": "field",
"ip": [
"8.8.8.8"
],
"outboundTag": "proxy"
},
```
进行路由分流.
**其余模式(如local DOH …
=> fixed XTLS#104 and apply routing for non-local DoH requests

app/dns/server.go, app/router/condition.go, common/protocol/tls/sniff.go, proxy/trojan/server.go, proxy/vless/inbound/inbound.go
fix https://github.com/XTLS/Xray-core/issues/192
=> convert domain names to lowercase when matching

transport/internet/tcp/hub.go
=> Fix ALPN being set to h2 by default when using TCP

app/reverse/portal.go
至少检查了一下连接是否还可用，原先当同一个portal处理两个以上的bridges的时候，先连接的bridge掉线了还会被pick到，直到它被间隔30秒执行一次的cleanup清理掉。
=> Fix available mux picker

core/config.go, main/run.go
修复了 1b87264c532b8e250e5098b15fc0b29d7f551e6e 导致文件读取不遵守 format 参数的问题
=> fix: fix format flag not working

README.md
Remove third party tap support since the xray has entered into the official homebrew/core
=> Remove third party homebrew tap support

transport/internet/websocket/dialer.go, transport/internet/websocket/dialer.html, transport/internet/websocket/hub.go
https://github.com/v2ray/discussion/issues/754#issuecomment-647934994 基于一年前的想法，原生 JS 实现了简洁的 WSS Browser Dialer，真实浏览器的 TLS 指纹
不过 WSS 仍存在 ALPN 明显的问题，所以下一步是浏览器转发 gRPC、QUIC
创造了一个非常简单、巧妙的通信机制：
1. Xray 监听地址端口 A，作为 HTTP 服务，浏览器访问 A，加载网页中的 JS
2. JS 主动向 A 建立 WebSocket 连接，成功后，Xray 将 conn 发给 `channel`
3. 需要 dial 时，Xray 从 `channel` 接收一个可用的 conn，并发送目标 URL 和可选的 early data
4. JS 成功 dial 目标后告知 Xray，并继续用这个 conn 全双工双向转发数据，连接关闭行为同步
5. 注意这个 conn 用过了就会被关闭，但 JS 会确保始终有新空闲连接可用
根据浏览器的需求，对 early data 机制进行了如下调整：
1. 服务端响应的 header 会带有请求的 `Sec-WebSocket-Protocol`，这也初步混淆了 WSS 握手响应的长度特征
2. 用于浏览器的 early data 编码是 `base64.RawURLEncoding` 而不是 `StdEncoding`，服务端做了兼容
此外，由于 https://github.com/XTLS/Xray-core/pull/375 推荐 `?ed=2048`，这个 PR 顺便将服务端一处 MaxHeaderBytes 扩至了 4096（虽然好像不改也没问题）
这是一个探索的过程，目前两边都是 Xray-core v1.4.1 时的配置方式：
1. …
=> WSS Browser Dialer

transport/internet/grpc/dial.go
Now dial using the proper IPv6 address (without []).
=> fix grpc dial ipv6 address

transport/internet/tls/config.go
the same fix with https://github.com/v2fly/v2ray-core/pull/998
由于上述pr内做了很多讨论和修改，所以为了清晰，这里简单总结一下：
1. 此PR修复https://github.com/v2fly/v2ray-core/issues/997 （此bug在Xray中同样存在）
2. 修复bug的同时，将生成证书的提前时间从1分钟增加为2分钟。为的是在VMess协议允许的C/S两端时间误差（90s）内，保证生成的证书依旧可用
3. 在生成证书和丢弃证书时，输出相应日志信息，便于排查相关问题
=> Fix: new cert issuing is incorrectly delayed

transport/internet/grpc/config.go, transport/internet/grpc/dial.go, transport/internet/grpc/encoding/customSeviceName.go, transport/internet/grpc/hub.go
=> gRPC: Use `PathEscape` encoded service name

testing/scenarios/common.go, testing/scenarios/vmess_test.go
I will try fixing some flaky tests, start with https://github.com/XTLS/Xray-core/runs/3605024544?check_suite_focus=true
This test can fail randomly for two reasons:
1. The server core and client core could try to listen on the same port, cause one core fail
2. The server listen for three ports, some might not be available
To fix first problem, I change it so that server will run first. I open another dokodemo inbound and test it is available before creating the client core.
For 2, I added a loop for server core to try pickPort() for 5 times if it failed.
I also fix the tcpConnAvailableAtPort() method and it is running much faster.
=> Fix flaky TestVMessDynamicPort

testing/scenarios/dokodemo_test.go, testing/scenarios/feature_test.go, testing/scenarios/shadowsocks_test.go, testing/scenarios/transport_test.go, testing/scenarios/vmess_test.go
https://github.com/XTLS/Xray-core/pull/731/checks?check_run_id=3713499282
Some tests try to listen udp port, but the port maybe not available.
=> Fix some tests to use udp.PickPort()

core/format.go, infra/vformat/main.go
Found an issue in format.go. It currently only work with `go run infra/vformat/main.go`
Fix by porting logic from vprotogen.
=> Fix go generate core/format.go

app/dns/dohdns.go, common/buf/multi_buffer_test.go, common/common.go, common/log/logger_test.go, common/ocsp/ocsp.go, infra/conf/serial/loader.go, infra/vformat/main.go, infra/vprotogen/main.go, main/commands/all/api/shared.go, main/commands/all/convert.go, main/confloader/external/external.go, main/run.go, proxy/shadowsocks/protocol.go, proxy/vmess/encoding/server.go, testing/scenarios/common.go, testing/scenarios/feature_test.go, testing/scenarios/http_test.go
XTLS is currently based on Go 1.17, so it is safe to remove deprecated ioutil package, ref v2fly/v2ray-core#1298 and https://golang.org/doc/go1.16#ioutil.
=> Move from deprecated ioutil to os and io packages

app/router/strategy_leastping.go
Core setup router object first, when InjectContext() is called, observatory object is still null,
so observatory need to be injected after InjectContext()
=> Fix null pointer exception for observatory

transport/internet/quic/conn.go, transport/internet/quic/dialer.go, transport/internet/quic/hub.go
同步 v2fly/v2ray-core 上游修复： https://github.com/v2fly/v2ray-core/pull/1404
=> Fix net.UDPConn Error

common/units/bytesize.go, common/units/bytesize_test.go, testing/scenarios/common.go
Occasional error is observed when we execute long test
Print time and memory for better troubleshooting in the future
Co-authored-by: Jebbs <qjebbs@gmail.com>
=> Add statistics in conn testing

.github/workflows/release.yml, .github/workflows/test.yml
This PR adds specific permissions to the existing workflows under .github/workflows.
I am the founder of [Step Security](https://www.stepsecurity.io), and have implemented a [GitHub App](https://github.com/apps/step-security) to automatically restrict permissions for the GITHUB_TOKEN in workflows. This is a security best practice as per the GitHub Actions [hardening guide](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions). 
I am trying the App out on public repositories, by forking them, installing the App on the fork, and manually creating PRs with the fixed workflows. The App automatically fixes permissions when a new PR is created that creates a new workflow, so feel free to [install it](https://github.com/apps/step-security) for future …
=> Add specific permissions to workflows under .github/workflows

.github/workflows/release.yml, .github/workflows/test.yml
check-latest can make sure actions will always use the latest minor version of golang to build.
No manually update needed anymore.
=> workflows: add check-latest

app/metrics/metrics.go, app/metrics/outbound.go, features/stats/stats.go, testing/scenarios/metrics_test.go
This commit fixes an error in metrics handler when observatory is not enabled.
At the same time changes some typos found in stats.
=> fix: expvar error when observatory is not enabled & various typos

app/dispatcher/default.go, infra/conf/xray.go, transport/pipe/impl.go, transport/pipe/pipe.go
An updated version of @hmol233's original
https://github.com/XTLS/Xray-core/tree/fix/udp-sniffing
A map is used by server side when client turn on fakedns
Client will send domain address in the buffer.UDP.Address, server record all possible target IP addrs.
When target replies, server will restore the domain and send back to client.
CC  @nekohasekai  @badO1a5A90
=> Fakedns fix xUDP destination override

transport/internet/http/dialer.go, transport/internet/tls/tls.go
Hello
I was messing around with xray settings and realized that [utls](https://github.com/refraction-networking/utls) integration only works with raw tcp + tls configuration. So I thought maybe there is a way to bring utls to websocket/gRPC and http2!
Turns out, websocket and gRPC are not really handy to use utls in them. But http is really easy because we simply set DialTLS function and do it ourselves. So I added the ability to choose between `gotls.Client` and `utls.Client` and stablish the TLS with them.
To achieve a clean code, I added an interface to tls package which provides methods needed to initiate the tls connection. Unfortunately, `ConnectionState` method returns two different structs in gotls and utls so I had to create a method called `NegotiatedProtocol` to return the …
=> Added utls to http2 transport

transport/internet/tls/tls.go, transport/internet/websocket/dialer.go
Hello again
Well; I added utls this time to websocket which is far more popular than http2 and will be probably more used.
So lemme explain it a little because this pull request contains only additions and some of them are not really obvious. At first, I added a method called `WebsocketHandshake` to `UConn`. Why another method is needed? Because both Chrome and Firefox fingerprints have a very small difference depending on if the request is a websocket connection or a simple HTTP request.
[Chrome Fingerprint Difference](https://tlsfingerprint.io/compare/b8ddad74f1546398/e47eae8f8c4887b6)
[Firefox Fingerprint Difference](https://tlsfingerprint.io/compare/ad5407dfc7213726/b250617dca0ac79f)
As you can see, the only difference is in ALPN which for websocket, it only contains `http/1.1`. …
=> Added utls to websocket

transport/internet/grpc/dial.go, transport/internet/tls/grpc.go
Hello again
At the very end, I added uTLS to gRPC transport.
What I did to implement this, was that I copy and pasted [this lines of code](https://github.com/grpc/grpc-go/blob/v1.50.1/credentials/tls.go#L33-L146) from gRPC's library into `tls` package of xray. Then, I changed the go's TLS package with uTLS. I also made the `ServerHandshake` method to always panic because it's never called (because this is client's code!) and, well, we don't want uTLS to act as server. I can change this and simply copy and paste the `ServerHandshake` [code](https://github.com/grpc/grpc-go/blob/v1.50.1/credentials/tls.go#L113-L130) from gRPC's library to xray's code; But as I said, I think it's better to keep it this way.
One small change which I also done is this line: …
=> Added uTLS to gRPC

common/buf/multi_buffer.go, infra/conf/vless.go, proxy/vless/encoding/addons.go, proxy/vless/encoding/encoding.go, proxy/vless/inbound/inbound.go, proxy/vless/outbound/outbound.go, proxy/vless/vless.go
新流控实验选项：xtls-rprx-vision
- 解决已知漏洞
- 针对 tls1.3 开启 xtls (直接拷贝) 模式
- 增加 tls 握手长度混淆
- 简化代码
注意："streamSettings" "security" 必须使用 “tls” "tlsSettings" 不能使用 “xtls” “xtlsSettings”
=> Add XTLS RPRX's Vision

transport/internet/system_dialer.go, transport/internet/system_listener.go
如果配置中只设置了`"tcpKeepAliveInterval": -1`，而没有设置`"tcpKeepAliveIdle": -1`，xray不会设置goStdKeepAlive，导致后面dial或者accept的时候，keepalive配置被golang官方默认的覆盖。
=> Fix sockopt.TcpKeepAliveInterval

common/crypto/auth.go
Copied from https://github.com/v2fly/v2ray-core/pull/2032
Thanks to @nlzy
Close #1255
=> fix: replace "math/rand" with "crypto/rand" in padding generation

common/mux/client.go, common/mux/server.go
ray系的mux一直有一个老毛病，取消下载文件后流量还会继续跑，比如#232。
排查后发现问题出在`commom/mux/server.go`文件下的`handleStatusEnd`函数。
具体而言，`mux`客户端向服务端发送`End`状态请求结束对应的`mux.Session`时，服务端接受到该请求，并最终进入`handleStatusEnd`函数：
```
func (w *ServerWorker) handleStatusEnd(meta *FrameMetadata, reader *buf.BufferedReader) error {
if s, found := w.sessionManager.Get(meta.SessionID); found {
...
s.Close()
}
...
return nil
}
```
上述`if`语句中的`s.Close`函数：
```
func (s *Session) Close() error {
common.Close(s.output)
common.Close(s.input)
s.parent.Remove(s.ID)
return nil
}
```
分别调用`s.input`和`s.output`的`Close`方法，然后将该`session`的`ID`从`sessionmanager`中移除。
问题出现在，`s.input`是一个`pipe.Reader`，在xray中`pipe.Reader`没有实现`Close`方法，导致子连接无法正常断开，远程服务器会持续通过该`pipe.Reader`传输数据。
解决方法很简单，在`s.Close()`前手动中止`pipe.Reader`即可：
```
func (w *ServerWorker) handleStatusEnd(meta …
```
=> 修复mux子连接无法正常断开的问题

proxy/shadowsocks_2022/inbound_multi.go
@thank243 strings.ToLower will cause the email inconsistent, which makes XrayR unable to limit the speed and device. But I am not sure whether remove it would cause other issues in adding/deleting Shadowsocks2022 users.
=> fix: email inconsistent

transport/internet/grpc/dial.go, transport/internet/http/dialer.go, transport/internet/tcp/dialer.go, transport/internet/tls/tls.go, transport/internet/websocket/dialer.go
xray_random means to pick a random uTLS fingerprint at the core startup
This way, the fingerprint is stable for a user for some days. While there is no identifiable signature for the whole xray community
CC @RPRX
=> Add fingerprint xray_random

testing/scenarios/tls_test.go, transport/internet/tls/tls.go
As stated in the title, when client tries to use utls as tlsStream, and AllowInsecure has turned on, utls never checks for PinnedPeerCertificateChainSha256 leaving those using self signed certificate at risk.
tests added:
- TestSimpleTLSConnectionPinned (TestSimpleTLSConnectionPinned but with wrong certificate hash)
- TestUTLSConnectionPinned (TestSimpleTLSConnectionPinned but using fingerprint and utls)
- TestUTLSConnectionPinnedWrongCert (TestUTLSConnectionPinned but with wrong certificate hash)
=> utls not using PinnedPeerCertificateChainSha256

proxy/vless/inbound/inbound.go
=> Xtls vision reject vless-tcp-tls+Mux

transport/internet/udp/dispatcher.go
UDP dispatcher fails to handle the error raised by routing.Dispatcher, which could cause unexpected errors XrayR-project/XrayR#204.
=> fix: handle error raised by dispatcher

proxy/vless/encoding/encoding.go, proxy/vless/outbound/outbound.go
This only affect the Vision client for protocols expecting server to send data first.
The change is compatible with existing version of Vison server.
CC @RPRX
=> Insert padding with empty content to camouflage VLESS header

transport/internet/grpc/config.go, transport/internet/grpc/config_test.go, transport/internet/grpc/dial.go, transport/internet/grpc/encoding/customSeviceName.go, transport/internet/grpc/hub.go
In this PR, I added the ability to define custom full paths for gRPC as discussed in #1793. I added some tests as well just for the sake of it.
Here are two example configs:
Server:
```json
{
"log": {
"loglevel": "debug"
},
"inbounds": [{
"listen": "127.0.0.1",
"port": 12345,
"protocol": "trojan",
"settings": {
"clients": [{
"password": "123456"
}
]
},
"streamSettings": {
"network": "gun",
"security": "none",
"grpcSettings": {
"serviceName": "/my/sample/path/customTun|customTunMulti"
}
}
}
],
"outbounds": [{
"protocol": "freedom"
}
]
}
```
Client Tun:
```json
{
"log": {
"loglevel": "debug"
},
"inbounds": [{
"listen": "127.0.0.1",
"port": "10818",
"protocol": "socks"
}
],
"outbounds": [{
"protocol": "trojan",
"settings": {
"servers": [{
"address": "127.0.0.1",
"port": 12345,
"password": …
```
=> gRPC Custom Path

app/dns/dns.go, app/dns/dns_test.go, common/errors/multi_error.go, proxy/dns/dns.go
Sometimes previous DNS responds empty records.
This especially happens when a province/city level DNS respond with a 0.0.0.0
```
$ drill @202.101.224.68 www.binance.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 39119
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; www.binance.com.	IN	A
;; ANSWER SECTION:
www.binance.com.	30	IN	A	0.0.0.0
;; AUTHORITY SECTION:
;; ADDITIONAL SECTION:
;; Query time: 12 msec
;; SERVER: 202.101.224.68
;; WHEN: Wed Apr 26 22:56:42 2023
;; MSG SIZE  rcvd: 49
```
And it later got filtered by a downstream DNS server.
```
$ drill @192.168.9.1 www.binance.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 5425
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; …
```
=> fix: dns empty response

transport/internet/udp/dispatcher.go
this saves the passing ctx by func core.DialUDP
=> fix: udp.DialDispatch saves the c.ctx passing

.github/docker/Dockerfile
在需要自定义参数时可以省略输入 `/usr/bin/xray`，例如：
```bash
docker run --rm ghcr.io/xtls/xray-core /usr/bin/xray x25519
docker run --rm ghcr.io/xtls/xray-core x25519
```
=> 为 Dockerfile 设置 `ENTRYPOINT`

go.mod, go.sum, transport/internet/reality/linkname.go, transport/internet/reality/reality.go
This comes with other optimizations with current REALITY client implementation:
1. Reuse existing sessionId slice instead of allocating a new one.
2. Adjust sessionId processing order to eliminate bounds checks.
3. Cache the offset of `peerCertificates` to avoid reflection overhead.
=> REALITY protocol: Add ChaCha20-Poly1305 auth mode

infra/conf/freedom.go, proxy/freedom/freedom.go
Big shout-out to @sambali9 for taking the initiative to add fragmentation to the freedom project - nice one! I took a closer look, and it seems what we've got is TCP segmentation rather than fragmentation. The thing is, this doesn't quite work in Iran because of GFW's TCP reassembly capabilities. So, I've gone ahead and made some changes to shift from TCP segmentation to TLS Hello fragmentation.
Here's a sample configuration you can use for testing the new implementation:
```json
{
"log": {
"loglevel": "debug"
},
"inbounds": [
{
"listen": "0.0.0.0",
"port": "1083",
"protocol": "socks",
"settings": {
"auth": "noauth",
"udp": true,
"ip": "0.0.0.0"
}
},
{
"listen": "0.0.0.0",
"port": "1081",
"protocol": "http"
}
],
"outbounds": [
{
"protocol": "freedom",
"settings": {
"fragment": {
"length": …
```
=> Replace TCP Segmentation with TLS Hello Fragmentation

proxy/http/client.go
#2174 Patch potential nil pointer deference.
Inside ```proxy::http::client::fillRequestHeader()``` function, inbound and outbound metadata are extracted from the context object,
```go
inbound := session.InboundFromContext(ctx)
outbound := session.OutboundFromContext(ctx)
data := struct {
Source net.Destination
Target net.Destination
}{
Source: inbound.Source,
Target: outbound.Target,
}
```
However, both ```InboundFromContext``` and ```OutboundFromContext``` can return nil value, 
```go
func InboundFromContext(ctx context.Context) *Inbound {
if inbound, ok := ctx.Value(inboundSessionKey).(*Inbound); ok {
return inbound
}
return nil
}
```
and de-referencing them could panic the application. The error message reported by #2174 was triggered by nil inbound value.  It probably needs a separate …
=> #2174: fix: Patch potential nil pointer deference

common/net/destination.go
#2017 Panic due to nil dereferencing
While I was investigating #2017, I saw the error log reported by @base510 
```
2023/04/30 20:00:38 [Error] common/net: invalid IP format: []
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x982078]
goroutine 92630 [running]:
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).getUoTConnection(0xc0001d5ce0, {0x13eeb40, 0xc0008e5290}, {{0x0?, 0x0?}, 0x7f?, 0x0?})
github.com/xtls/xray-core/app/proxyman/outbound/uot.go:14 +0x58
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0xc0001d5ce0, {0x13eeb40?, 0xc0008e5290?}, {{0x0, 0x0}, 0xb, 0x2})
github.com/xtls/xray-core/app/proxyman/outbound/handler.go:214 +0xa26 …
```
=> #2017 fix: Check if address is nil for IsValid() function.

app/proxyman/outbound/uot.go, common/net/destination.go
My previous change: https://github.com/XTLS/Xray-core/pull/2335 made a bold assumption that in order for the destination to be valid, the IpAddress must not be nil. But throughout the code base, there might be places where the assumption is false, as the error log reported by @base510,
```
goroutine 47593 [running]:
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch(0xc0002203c0, {0x13bf960, 0xc0002264b0}, {{0x0, 0x0}, 0xb, 0x2})
github.com/xtls/xray-core/app/dispatcher/default.go:287 +0x519
github.com/xtls/xray-core/common/mux.(*Server).Dispatch(0x0?, {0x13bf960?, 0xc0002264b0?}, {{0x0?, 0x0?}, 0x11?, 0x0?})
github.com/xtls/xray-core/common/mux/server.go:41 +0xcf
...
```
For now we should revert the change and add the nil check in the function instead.
=> fix: revert previous change on IsValid() function

common/singbridge/destination.go, proxy/shadowsocks_2022/inbound_multi.go
This is following up the error log posted by @base510 in PR #2017.
The error log is as following,
```
panic: Dispatcher: Invalid destination.
goroutine 47593 [running]:
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch(0xc0002203c0, {0x13bf960, 0xc0002264b0}, {{0x0, 0x0}, 0xb, 0x2})
github.com/xtls/xray-core/app/dispatcher/default.go:287 +0x519
github.com/xtls/xray-core/common/mux.(*Server).Dispatch(0x0?, {0x13bf960?, 0xc0002264b0?}, {{0x0?, 0x0?}, 0x11?, 0x0?})
github.com/xtls/xray-core/common/mux/server.go:41 +0xcf
github.com/xtls/xray-core/proxy/shadowsocks_2022.(*MultiUserInbound).NewConnection(0xc0001c5500, {0x13bf960, 0xc0002263f0}, {0x13c5358, 0xc000224070}, {{0x120ab67, 0xb}, {{{0x0, 0xffff59745902}, 0xc000012120}, ...}, ...}) …
```
=> fix: correct the logic of converting Socksaddr into net.Destination.

.github/build/friendly-filenames.json, .github/workflows/release.yml, go.mod, go.sum
Bump github.com/refraction-networking/utls from 1.3.2 to 1.3.3 is necessary because it fixes build error on the loong64 port: https://github.com/refraction-networking/utls/pull/195
All build jobs passed: https://github.com/KatyushaScarlet/Xray-core/actions/runs/5572784642/jobs/10179217143
=> CI: Add Linux loong64 build task

core/config.go, main/run.go
既然 Xray/V2ray 内核支持可注释的 JSON，何不支持 jsonc 格式的文件呢？
例如 `config.jsonc` ，这样的文件在使用编辑工具打开时会自动识别为 JSON with Comments 文件，不会给注释报错
=> JSON with Comments (jsonc) ext file

proxy/shadowsocks/protocol.go, proxy/shadowsocks/protocol_test.go, proxy/shadowsocks/validator.go
Following up on the issue #2310 and the previous PR #2315, I did some investigation and found the length check is not necessary when the encryption is disabled, even though it's not very common use-case to disable encryption for Shadowsocks protocol. 
Given the current way the Shadowsocks header is parsed, the length check on the payload is only necessary when the validator decrypts the payload, in which there might be array out of bound exception. To fix the problem, I moved the length check inside the validator, such that if the payload size is too short, the validator wouldn't even attempt to decrypt the payload. Meanwhile, I added a set of unit tests to cover the change.
=> fix(proxy): removed the udp payload length check when encryption is disabled

transport/internet/grpc/config.go, transport/internet/grpc/config_test.go
Following up on #2460, it looks like the service name parsing assumes the service name string in the config file always contains more than 2 '/' characters, which is not always the case. 
```go
lastIndex := strings.LastIndex(c.ServiceName, "/")   // Might return 0
c.ServiceName[1:strings.LastIndex(c.ServiceName, "/")]  // Might become c.ServiceName[1:0] ==> slice bounds out of range [1:0]
```
And when it happens, the entire program would crash due to ```panic: runtime error: slice bounds out of range [1:0]``` error. To reduce the amount of application panic with error messages full of golang jargon, that create confusion to new users, I made it the service name parsing safe and would return empty string if it can't find any.
Meanwhile, since I am not too familiar with GRPC, I am not …
=> fix(config): fix grpc cofnig parsing when service name only has one '/' char

common/strmatcher/ac_automaton_matcher.go, common/strmatcher/strmatcher_test.go
DomainMatcher panic when dispatch invalid domain
```
Aug 22 11:58:48 cds04 xray[237757]: panic: runtime error: index out of range [189] with length 127
Aug 22 11:58:48 cds04 xray[237757]: goroutine 6439 [running]:
Aug 22 11:58:48 cds04 xray[237757]: github.com/xtls/xray-core/common/strmatcher.(*ACAutomaton).Match(...)
Aug 22 11:58:48 cds04 xray[237757]: #011github.com/xtls/xray-core/common/strmatcher/ac_automaton_matcher.go:228
Aug 22 11:58:48 cds04 xray[237757]: github.com/xtls/xray-core/common/strmatcher.(*MphMatcherGroup).Match(0xc0004e4900, {0xc001839cd0, 0xc})
Aug 22 11:58:48 cds04 xray[237757]: #011github.com/xtls/xray-core/common/strmatcher/mph_matcher.go:186 +0x39b
Aug 22 11:58:48 cds04 xray[237757]: github.com/xtls/xray-core/app/router.(*DomainMatcher).ApplyDomain(0xc000265650, …
```
=> fix(common): strmatcher match domain safety

transport/internet/grpc/hub.go, transport/internet/http/hub.go, transport/internet/system_listener.go, transport/internet/tcp/hub.go, transport/internet/websocket/hub.go
The unix domain socket locker file would not be [released](https://github.com/XTLS/Xray-core/blob/dca57aab2669ffdff5fc87020e41899f548d8308/transport/internet/filelocker_other.go#L27) after closing listener.
That's because the context value set by the child cannot be obtained by the parent. And the current logic is a bit complex, we have to add the logic to release locker file everywhere we have used normal unix domain socket.
=> fix(transport): correctly release UDS locker file

app/dispatcher/default.go
`strings.HasPrefix(p, protocolString)` is for `strings.HasPrefix("fakedns+others", "fakedns")`.
I tested that "fakedns+others" does not work at all so this fix is in fact meaningless, only making "fakedns+others" identical to "fakedns". Maybe you can remove related code.
related:
https://github.com/v2fly/v2ray-core/commit/1b0e046
https://github.com/v2fly/v2ray-core/compare/9bbc3af...3c0aff7 (incorrect fix)
=> fix typo in default.go

README.md
Streisand is a free iOS client with Xray-Core v1.8.4 support, offering routing and custom DNS features.
=> Add Streisand to README/GUI Clients

infra/conf/xray.go, infra/conf/xray_test.go
when use multi config file inbounds not appends :
` ./xray -c config.json -c config2.json -c config3.json`
issue mentioned in https://github.com/XTLS/Xray-core/issues/2606
=> Override inbounds in multi config files

infra/conf/xray.go, infra/conf/xray_test.go
seems override outbounds should also consider in  last PR https://github.com/XTLS/Xray-core/pull/2655
=> Override outbounds in multi config files

transport/internet/quic/dialer.go
Issue #2605 brought up real problem that QUIC dialer doesn't support sockopt at the moment. Inside `internet.DialSystem(...)` function, one of the branch that involves `redirect(...)` returns `cnc.connection` instance that is currently unhandled by the code logic, and thus caused program panic during runtime.
```go
rawConn, err := internet.DialSystem(ctx, dest, sockopt)
```
```go
// DialSystem calls system dialer to create a network connection.
func DialSystem(ctx context.Context, dest net.Destination, sockopt *SocketConfig) (net.Conn, error) {
...
if obm != nil && len(sockopt.DialerProxy) > 0 {
nc := redirect(ctx, dest, sockopt.DialerProxy)
if nc != nil {
return nc, nil
}
}
...
}
```
It seems the sockopt support for QUIC protocol requires a couple changes including making …
=> #2605: Add safety check for type casting for QUIC dialer

transport/internet/websocket/hub.go
开ws的时候如果连接数过多xray会莫名其妙多吃很多内存 似乎是由于issues里的问题 改掉以后ram占用好像确实会减少(WTF)
见 https://github.com/gorilla/websocket/issues/223
=> 优化ws多并发时的表现

README.md
Add link to tutorial for "Xray with WireGuard inbound" using the new WireGuard inbound feature added in Xray-core v1.8.6.
=> Add link to tutorial for "Xray with WireGuard inbound"

common/ocsp/ocsp.go
This fixes a dropped `err` variable in `common/ocsp`.
=> common/ocsp: fix dropped error

main/commands/all/commands.go, main/commands/all/curve25519.go, main/commands/all/wg.go, main/commands/all/x25519.go
```console
❯ ./xray help wg
usage: xray wg [-i "private key (base64.StdEncoding)"]
Generate key pair for wireguard key exchange.
Random: xray wg
From private key: xray wg -i "private key (base64.StdEncoding)"
❯ ./xray wg
Private key: eM02wAO5f1uVTXSD+TcbSlcV0h2YPmde0zOZk1Hy+z8=
Public key: UFZNg9/XHkLdtrzlov3hTIevmMYf8eHhSLC9SM0tQ0M=
❯ ./xray wg -i eM02wAO5f1uVTXSD+TcbSlcV0h2YPmde0zOZk1Hy+z8=
Private key: eM02wAO5f1uVTXSD+TcbSlcV0h2YPmde0zOZk1Hy+z8=
Public key: UFZNg9/XHkLdtrzlov3hTIevmMYf8eHhSLC9SM0tQ0M=
```
```console
❯ echo eM02wAO5f1uVTXSD+TcbSlcV0h2YPmde0zOZk1Hy+z8= | wg pubkey
UFZNg9/XHkLdtrzlov3hTIevmMYf8eHhSLC9SM0tQ0M=
```
=> Command: Add `wg` for wireguard key generation

proxy/shadowsocks_2022/outbound.go
新版sing中删除了StackNew()，需要使用New()
=> Fix deprecated StackNew() function

go.mod, go.sum, proxy/shadowsocks_2022/inbound.go, proxy/shadowsocks_2022/inbound_multi.go, proxy/shadowsocks_2022/inbound_relay.go, proxy/shadowsocks_2022/outbound.go
#2805 fixed compatibiltiy with newer SagerNet/sing versions. However, it is not a complete upgrade and only removed the usage to a removed function, and there are some deprecated functions still in use which should be migrated.
This PR updated sing to v0.3.x beta versions, removed stack buffer related codes, improved some buffer release scenarios and migrated FullReset usage.
=> Cleanup sing buffer usage

transport/internet/sockopt_windows.go
Currently interface setting is ignored under Windows.
To enable bindToInterface under Windows by refering to
https://github.com/SagerNet/sing/blob/dev/common/control/bind_windows.go
https://github.com/WireGuard/wireguard-go/blob/5846b622837e04dbc35b153d9ceda7fd66397520/conn/bind_windows.go#L567
=> Enable interface setting for socketopt under Windows

app/proxyman/outbound/handler.go, proxy/wireguard/client.go, transport/internet/dialer.go, transport/internet/system_dialer.go
Android client prepares an IP before proxy connection is established. It is useful when connecting to wireguard (or quic) outbound with domain address. E.g. engage.cloudflareclient.com:2408
=> Add DestIpAddress() in Dialer interface

common/log/logger.go, common/reflect/marshal.go, common/reflect/marshal_test.go, core/config.go, infra/conf/serial/builder.go, main/run.go
目前多文件配置合并后的配置无法导出，如果出错很难排查。比如文档中写2个或以上outbounds覆盖前者，然而实际情况是仅追加。这个PR在`run`命令中添加`-dump`子命令，用于导出合并后的配置。输出的是json格式的`infra/conf/Config`。目前只支持合并json文件格式，不支持protobuf也不支持从`stdin:`读取配置。  
使用 https://xtls.github.io/config/features/multiple.html#%E5%A4%9A%E6%96%87%E4%BB%B6%E5%90%AF%E5%8A%A8 里面的配置作为例子，执行`./xray run -dump --confdir=confs`命令，输出以下内容：  
```json
{
"InboundConfigs": [
{
"PortList": {
"Range": [
{
"From": 4321,
"To": 4321
}
]
},
"Protocol": "socks",
"Settings": null,
"Tag": "socks"
},
{
"Protocol": "http",
"Settings": null,
"Tag": "http"
}
],
"InboundDetours": [],
"OutboundConfigs": [],
"OutboundDetours": [],
"Port": 0
}
```
合并两个复杂点的配置：  
```json
{
"API": {
"Services": [
"StatsService"
],
"Tag": "api"
},
"InboundConfigs": [
{
"PortList": {
"Range": [
{
"From": 3307,
"To": 3307
}
]
}, …
```
=> Add sub-command "-dump" to "run".

.github/workflows/release.yml, .gitignore, Makefile, README.md
=> Feat: Using `Makefile` to build xray

common/singbridge/dialer.go
This picks up a dropped `ctx` variable passed into `XrayOutboundDialer.DialContext()` but then never used.
=> common/singbridge: fix dropped context

app/proxyman/outbound/outbound.go
as mentioned https://github.com/XTLS/Xray-core/issues/2898#issuecomment-1880261654
outbound selector tags output may not run by order in :
https://github.com/XTLS/Xray-core/blob/3f0bc134298cf512bd29660221a030db91594faf/app/proxyman/outbound/outbound.go#L150
as mentions in golang ref 
See https://golang.org/ref/spec#For_statements
`The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next. If a map entry that has not yet been reached is removed during iteration, the corresponding iteration value will not be produced. If a map entry is created during iteration, that entry may be produced during the iteration or may be skipped. The choice may vary for each entry created and from one iteration to the next. If the map is nil, the number …
=> sort Outbound selector output

app/proxyman/outbound/outbound.go, app/router/balancing.go
负载均衡从outbounds manager获取tags时，很多时候返回的tags是相同的。这个PR给ohm.Select()添加缓存，减少sort次数。
=> Add tags cache to app.proxyman.ohm.Select()

testing/scenarios/dokodemo_test.go, testing/scenarios/shadowsocks_2022_test.go, testing/scenarios/shadowsocks_test.go, testing/scenarios/vmess_test.go
In the past, the UDP test in mass parallel proved to be the source of instability. This change try to improve pass rate.
=> Reduce size and time of UDP test

app/proxyman/outbound/handler_test.go, app/proxyman/outbound/outbound.go
这个PR修复ohm.Select()中并发写tagsCache报错的问题。
@deorth-kku 谢谢反馈 https://github.com/XTLS/Xray-core/pull/2927#issuecomment-1893123058
=> Fix concurrent map writes error in ohm.Select().

.github/workflows/release.yml, .github/workflows/test.yml
Use [go version file to get go version](https://github.com/actions/setup-go/tree/main?tab=readme-ov-file#getting-go-version-from-the-gomod-file) instead of manually specifying.
=> chore(ci): use go version file to specify the go version

common/crypto/auth.go
一个 安全漏洞(大概是深夜敲代码不小心写错了罢) https://github.com/v2fly/v2ray-core/releases/tag/v5.14.0
=> Correctly propagate error in AuthenticationReader readBuffer

infra/conf/router.go
These codes seems useless, because it can be replace by using this example:
```jsonc
{
"domain": "geosite:cn",
"outboundTag": "direct"
},
{
"ip": "geoip:cn",
"outboundTag": "direct"
}
```
I think we can remove these codes without worries of breaking.
=> Chore: Clean up legacy `field` usage

transport/internet/httpupgrade/connection.go, transport/internet/httpupgrade/hub.go
=> Fix(httpupgrade): `X-Forwarded-For` header not read.

infra/conf/xray.go
问题: 当`burstObservatory`项不在第一个配置文件中时，将丢失。
修复`burstObservatory`项在多配置文件中无法覆写问题。
=> fix: config `burstObservatory` override

infra/conf/transport_internet.go
=> 修复HTTPUpgrade在headers设置host不生效的问题

main/commands/all/api/api.go, main/commands/all/api/source_ip_block.go
add Source IP Block command for clients. x-ui and ...
kinda help for ip restriction.
`./xray api sib --server=127.0.0.1:62789 -outbound=blocked -inbound=socks5 -reset 127.0.0.1 1.1.1.1 ...`
```go
-outbound
route traffic to specific outbound.
-inbound
target traffig from specific inbound.
-ruletag
set ruleTag. Default sourceIpBlock
-reset
remove ruletag and apply new source IPs. Default false
```
https://github.com/XTLS/Xray-core/pull/1317
=> API: add Source IP Block command

transport/internet/reality/reality.go, transport/internet/tls/config.go
只需要 在SNI项填入 ```nosni```  客户端就不会再发送这个扩展
```
"serverName": "nosni",
"allowInsecure": true
```
由于gotls本身的限制，如果SNI为空则必须启用Insecure.
=> 允许不向服务端发送SNI

app/proxyman/outbound/handler.go
Optimize the random IP algorithm logic and fix the problem of random IP errors when the prefix is not divisible by 8.
=> Fix IPv6 random IP logic error

Makefile
On macOS it's possible to compile both x86_64 and aarch64 binaries and then merge them together to produce universal build. It doesn't seem possible to achieve without passing `GOARCH` and `GOOS` into the `go build` command, so this PR re-exports those env variables and tweaks the binary name to reflect the architecture.
Example usage:
```sh
XRAY_SRC_DIR="<path to xray-core checkout>"
GOOS=darwin GOARCH=amd64 make -C "$XRAY_SRC_DIR"
GOOS=darwin GOARCH=arm64 make -C "$XRAY_SRC_DIR"
local amd64_bin="$XRAY_SRC_DIR/xray-amd64"
local arm64_bin="$XRAY_SRC_DIR/xray-arm64"
local fat_bin="$XRAY_SRC_DIR/xray"
lipo -create "$amd64_bin" "$arm64_bin" -output "$fat_bin"
```
=> Makefile: export GOARCH, GOOS

common/platform/platform.go, transport/internet/websocket/dialer.go, transport/internet/websocket/dialer.html
Fix https://github.com/XTLS/Xray-core/issues/3236
Validate the origin of inbound websocket requests by default.
If the user wants to change origin validation, they can set `XRAY_BROWSER_DIALER_ORIGIN=http://custom.localhost.net:3000`
The current implementation is very inconvenient, because the origin is validated very strictly. If `XRAY_BROWSER_DIALER=http://127.0.0.1:3000`, then the user has to visit `127.0.0.1`, not `localhost`. Is there a function to normalize this difference? Should xray perform DNS requests to normalize host names (I think this could open more attack vectors, using DNS rebinding)
=> Validate /websocket requests from browser dialer page

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/bug_report_zh.yml
本来希望大家都会看说明 结果加了模板之后发现基本都把说明要求提供config当耳边风 然后日志没加必填也基本全是no response
没办法 全部加上了 还弄了了一个代码块和折叠 免得看到辣眼睛的复制 这样可能好一点点
=> 完善 issue 模板

proxy/socks/server.go, proxy/socks/udpfilter.go
虽然这个漏洞无关痛痒不过多少是个安全漏洞 还是想办法修了
不改变现有的UDP处理结构(UDP还是听在TCP同端口)
=> 修复socks5密码可以被绕过的漏洞

transport/internet/websocket/ws_test.go
https://github.com/XTLS/Xray-core/pull/3412#issuecomment-2144264833
=> Make ws_test uses random ports

transport/internet/httpupgrade/dialer.go
it seems the recently added httupgrade testsuite is causing timeouts on master
i have no evidence this is the real issue, but it feels to me that the server could accidentally over-read, and then the encapsulated connection will block forever trying to read data
let's test it in CI a couple of times, i don't have a way to reproduce the issue
=> drain buffer correctly in httpupgrade

infra/conf/transport_internet.go, transport/internet/httpupgrade/dialer.go
昨晚上看到就知道怎么搞了 感觉没必要就没动 没想到第二天起来看到还写了个这么复杂的玩意的
个人觉得还是有一点点必要维持可读性的（）
=> HTTPUpgrade send headers with specified capitalization

transport/internet/splithttp/dialer.go
https://github.com/XTLS/Xray-core/discussions/3373#discussioncomment-9804979
I know 1.21 is not really supported, but the fix is very simple. it seems unnecessary to force the user to change this all the time.
perhaps there can be a minimal build for go 1.21 that does not get new transports? but then, enforced in CI. as chise suggested.
=> fix compatibility issues with go 1.21

transport/internet/splithttp/dialer.go, transport/internet/splithttp/hub.go, transport/internet/splithttp/lazy_reader.go
as discussed at the end of #3412 
* querystring is gone, path is my new friend. `/<session>` and `/<session>/<seq>` is used. this is really conservative when it comes to special characters required, but it's difficult to extend IMO
* "early data" is implemented, the client can now send GET and POST at the same time. the server spawns another goroutine per session, which cleans up the session if the GET request has not been sent within 30 seconds.
* I found my use of `ctx` incorrect, and this caused randomly cancelled requests. This is a bug in 1.8.15 as well. Fixed it by using `context.WithoutCancel`, and making sure that `dialContext` uses `ctxInner` instead of the outer scopes' context
**This PR is a breaking change from 1.8.15**. Server 1.8.15 is incompatible with client 1.8.16, and …
=> next iteration on splithttp

.github/workflows/docker.yml
push tags for:
* every SHA on master, format `sha-<shortid>`
* every release, format `1.8.16`
right now it is hard to pin a version in my infrastructure, because basically nothing is tagged.
=> More docker tags

transport/internet/splithttp/dialer.go, transport/internet/splithttp/hub.go, transport/internet/splithttp/splithttp_test.go
Partially address https://github.com/XTLS/Xray-core/issues/3464
H2C support is required so that fallbacks can work with splithttp at all. **fallback with `path`-based routing still doesn't work.**
=> splithttp: Add support for H2C and http/1.1 ALPN on server

transport/internet/splithttp/upload_queue.go, transport/internet/splithttp/upload_queue_test.go
splithttp的Read()应该使用阻塞模式，不然trojan和VLESS读取第一个数据包时会返回长度为0
=> splithttp Read() using blocking mode

.github/workflows/release.yml, .github/workflows/test.yml, go.mod
Relevant discussions:
* https://github.com/XTLS/Xray-core/pull/3455
* https://github.com/XTLS/Xray-core/discussions/3373
Important point:
> 仅提供编译，无其它支持
> Only compilation is provided, no other support
----
TODO:
=> Add a Windows 7 build

transport/internet/httpupgrade/httpupgrade_test.go, transport/internet/splithttp/splithttp_test.go, transport/internet/websocket/connection.go, transport/internet/websocket/ws_test.go
似乎在 https://github.com/XTLS/Xray-core/commit/c8f6ba9ff0fd346543b8c2580247cf00b2e5655b 删掉了看起来不必要的远程IP字段改为直接从conn读取 但是这个字段用于传递X-Forwarded-For里的信息 直接读等于无视了这个头里的信息 导致了https://github.com/XTLS/Xray-core/issues/3545
=> 修复ws X-Forwarded-For 读取

transport/internet/splithttp/hub.go, transport/internet/splithttp/splithttp_test.go
It seems SH can't receive a short message too fast
=> Fix SplitHTTP race condition when creating new sessions

transport/internet/splithttp/hub.go, transport/internet/splithttp/splithttp_test.go
我不知道为什么会有人尝试直连 SplitHTTP3 而不去使用 tuic, hysteria 或者直接用 quic transport ，不过我去实现一下也不会有什么坏处。或许我应该直接加一个 UpDownSplit 用于使上下行各自用一个连接。
让 tlssettings.alpn 只有 ["h3"] 即可使用 SplitHTTP3 Server，虽然说一个正常的服务器支持了 h3 也应该支持 h2 和 http/1.1 ，不过其他的 QUIC 协议都没有这么做，所以我不在意，试试加两个 inbound
或许考虑一下 RFC 9220: Bootstrapping WebSockets with HTTP/3 会更好。
此提交使用原版 quic-go 而不是 uQuic ，与 #3550 平行。
=> SplitHTTP: Server supports HTTP/3

transport/internet/splithttp/dialer.go
https://t.me/projectXray/3782602
=> Fix: do not leave empty connetion

transport/internet/httpupgrade/httpupgrade_test.go, transport/internet/websocket/ws_test.go
These were copypasted to splithttp tests and then removed there
I can't imagine what they were supposed to do, the tests run fine without
=> Remove unnecessary sleep from test

.github/docker/Dockerfile, .github/workflows/docker.yml
1. Add multi-arch builds (386, amd64, arm, arm64, loong64, mips, mips64, mips64le, mipsle, ppc64, ppc64le, riscv64, s390x):
Replace `alpine` with `chainguard/static`, which contains only tzdata and ca-certificates without any ELF binaries, can be built with multi-arch static binaries.
https://hub.docker.com/r/chainguard/static
2. Use official geoip and geosite by default:
Default tags use official geoip and geosite, and this is consistent with the Release version.
https://github.com/XTLS/Xray-core/pull/3580
Such as: `latest, 1.8.21, main, sha-c07e022`
3. Add Loyalsoldier flavor:
Loyalsoldier flavor tags with suffix `-loyalsoldier` or `-l` (short for Loyalsoldier) use the third-party Loyalsoldier geoip and geosite.
Such as: `latest-loyalsoldier, latest-l, 1.8.21-loyalsoldier, 1.8.21-l, …
=> Docker: Add multi-arch builds and Loyalsoldier flavor

common/reflect/marshal.go, common/reflect/marshal_test.go, infra/conf/serial/builder.go
这个 PR 对 common/reflect/marshal.go 里面的 MarshalToJson() 做了以下优化了：
* enum 由原来的显示数字改为显示变量名
* 设置了 json 标签的 struct 字段，改为显示 json 标签内容
* 不显示空值、空字符串 或者 设置了 json:"omitempty" 的零值
* IP 地址由原来的显示数组 [127, 0, 0, 1] 改为显示字符串 "127.0.0.1"
* 端口列表由原来的显示结构体改为显示字符串
* 添加参数控制是否显示 `_TypedMessage_` 项
一个简单的样例：
```json
{
"account": {
"cipherType": "CHACHA20_POLY1305",
"password": "shadowsocks-password"
},
"email": "love@v2ray.com"
}
```
之前是这样：
```json
{
"Account": {
"CipherType": 7,
"IvCheck": false,
"Password": "shadowsocks-password",
"_TypedMessage_": "xray.proxy.shadowsocks.Account"
},
"Email": "love@v2ray.com",
"Level": 0
}
```
<details>
<summary>更详细的样例</summary>
<table>
<tr>
<td> config.json </td> <td> ./xray.exe -c config.json -dump </td>
</tr>
<tr>
<td>
```json
{
"log": {
"loglevel": "debug"
},
"inbounds": [
{ …
```
=> API: Improve MarshalToJson() in common/reflect/marshal.go

proxy/freedom/freedom.go
https://github.com/XTLS/Xray-core/pull/3660#issuecomment-2277473149
当interval为0时把分片写在一个包（同3660 简单一些 同时复用length等参数）
为什么不用 -1？
因为里面的值是uint（无符号整数） 不想改。 break proto是个坏习惯（吗）
TODO: support interval: 1/2(这必须要改类型了 那还不如把楼上改成int 如果有人做的话记得把值从0改成-1)
=> Send tls fragment in one tcp packet if interval is zero

transport/internet/splithttp/dialer.go
Copy the settings from QUIC transport. See
https://github.com/XTLS/Xray-core/pull/3565#issuecomment-2264356688 -- Tested with CDN and it seems better than before (fewer reconnections)
Keep-alive packets are still turned off, so the original concern of that PR should still be resolved.
=> SplitHTTP client: Raise idle timeout to 5 minutes

transport/internet/splithttp/hub.go
https://github.com/XTLS/Xray-core/pull/3643#issuecomment-2282304185
It makes sense. In earlier discussions of breaking changes, we assumed the server updates much faster than the client. But this is easy to do.
Note: `responseFlusher.Flush()` could also be conditional. It would mean that HTTP response headers are only written when the first VLESS response byte is written. For some CDN this is already the case. I am not sure what is preferred from a padding perspective. I guess technically response X-Padding can be removed if `responseFlusher.Flush()` is removed, and VLESS brings its own padding in the future. Anyway, I don't want to change it right now, because I am not sure if it triggers different timeout settings in the CDN. It can be changed later, it's not a breaking change.
=> SplitHTTP server: Only "ok" to older clients

common/reflect/marshal.go, main/commands/all/api/shared.go
I think this is better @vrnobody
=> Command: use reflect marshal to json as output

transport/internet/splithttp/dialer.go, transport/internet/splithttp/splithttp_test.go, transport/pipe/impl.go, transport/pipe/writer.go
Since https://github.com/XTLS/Xray-core/pull/3603 and https://github.com/XTLS/Xray-core/pull/3611, iperf and speedtest are triggering "too large upload" by the server. This is because v2ray's MultiBuffer pipe can actually return data larger than the configured size limit.
I'm surprised nobody noticed it so far. In principle, any heavy upload could disrupt the entire connection. In its infinite wisdom, speedtest.net hides such errors and only shows low upload instead. I only noticed this issue myself when inspecting server logs.
=> SplitHTTP: Do not produce too large upload

transport/internet/splithttp/client.go, transport/internet/splithttp/dialer.go, transport/internet/splithttp/hub.go, transport/internet/splithttp/lazy_reader.go, transport/internet/splithttp/splithttp_test.go, transport/internet/splithttp/strip_ok_reader.go, transport/internet/splithttp/upload_queue.go
There are a few bugs that are fixed here:
1. (all http versions) When the client opens a connection and closes it without any traffic, the Close would lock forever and not appear on the wire at all
2. (all http versions) When the client terminates the connection correctly, the server would not notice and keep the upload queue and related datastructures around until the proxied connection times out.
3. (quic only) closing the connection might crash the client as well, Fix https://github.com/XTLS/Xray-core/issues/3699
Are fixed in the following way:
* Problem 1 is addressed by removing the use of LazyReader. It turns out that while `ok` is being peeked, `Close` is entirely ignored
* Problem 2 is addressed on the server by using the request's context to close the connection
* Problem 3 is …
=> SplitHTTP: Fix connection leaks and crashes

common/mux/server.go, common/mux/server_test.go, common/session/context.go
Fix https://github.com/XTLS/Xray-core/issues/116
This issue does not appear at all if mux.cool is disabled. Maybe the issue can be avoided if routing is disabled too, but it's possible that the same issue appears elsewhere.
I have debugged this issue in prod with a lot of print statements, and can confirm that this patch fixes it. ~~Tests should be added. ***The mux server has no tests at all!***~~
Step-by-step:
1. The mux server is calling handleStatusNew with the same context multiple times. That function then calls w.dispatcher.Dispatch
2. Dispatch assigns some values specific to the connection onto the outbound here: https://github.com/XTLS/Xray-core/blob/83eef6bc1f554be84aeb799417688a070cd32ab8/app/dispatcher/default.go#L241-L242
3. Because the outbounds array on the connection …
=> Fix data leak between mux.cool connections

proxy/freedom/freedom.go
通过 `UseAlternativeSystemDialer` 或 `RegisterDialerController` 使用自定义 dialer 替换 `DefaultSystemDialer` 后，自定义 dialer 返回的 `net.Conn` 没有保证可以断言为 `*PacketConnWrapper`。
以 v2rayNG（AndroidLibXrayLite）为例，其自定义 dialer 返回的 `net.Conn` 可以被断言为 `*net.UDPConn` 但不能被断言为 `*PacketConnWrapper`，`NewPacketReader` 和 `NewPacketWriter` 断言失败， `PacketReader` 和 `PacketWriter` 不会被使用。
上下文：https://github.com/XTLS/Xray-core/pull/3711#issuecomment-2308644397 ，需要由真正的 v2rayNG 用户测试这在 v2rayNG 上是否有效。
=> Freedom: Fix PacketReader/PacketWriter type assertion

infra/conf/xray.go, infra/conf/xray_test.go
These things seem entirely undocumented, make it a hard error to set them.
=> Config: Remove legacy `inbound/outbound/detours`

transport/internet/reality/reality.go
在尝试解决 https://github.com/XTLS/Xray-core/issues/2896 的时候 稍微调试了一下，发现 `uConn.HandshakeState.State13.EcdheKey` 竟然是nil, 调查后发现 utls 的安卓11指纹（实为OkHttp）是仅TLS 1.2的 (见 https://github.com/refraction-networking/utls/blob/23de245734c7c25b11200f8b5859c2114c032e51/u_parrots.go#L1595 因为它没有 `SupportedVersionsExtension` 扩展) 连TLS1.3都不是  `EcdheKey` 自然就是nil了 继续尝试调用其ECDH方法自然就导致了空指针panic
我认为这是utls库的一个错误，因为OkHttp在安卓10就默认使用了TLS13 不过考虑到可能还有其他仅TLS12的指纹 被random到踩到坑 还是在Xray这边检测并返回错误 避免直接panic比较好
闲的话可以把服务器证书换成GTS签发的 然后用android指纹 会因为使用TLS12导致证书泄露 GFW看到GTS的证书就会把服务器IP阻断几分钟 ~~我本地测试的时候发现的~~
=> Fix: Return error when Fingerprint does not support TLS 1.3

proxy/vmess/validator.go
…protocol user in an inbound proxy. If inTag: "VMess-xxx", but the developer carelessly calls the add user method of vless or other protocols, such as xrayCtl.AddVlessUser(user), causing xray panic
=> Fix: RPC call causes xray panic problem using wrong account type

app/dns/nameserver_doh.go, app/dns/nameserver_quic.go, app/dns/nameserver_tcp.go, app/dns/nameserver_udp.go
见 #1231 
原代码里写的是 如果没有found到 就跳过缓存(if err != errRecordNotFound)
但是如1231中的问题 它确实found到了 但是found的是什么? found到了一个 `rcode 3`（摊手）
修改之后只要遇到错误就绕过缓存 重新解析 代码里还豁免了一种情况 `dns_feature.ErrEmptyResponse`  因为这个错误表示没hit对 比如指定解析ipv4 但是解析出来只有v6 这种情况我们它是正常的 不然的话正常单栈v6会被认为解析失败而反复解析
但是注意 现在被修改之后对于一些无效的请求 每一次xray都会进行转发而不会cache住 可能会多大量不必要的无效请求
其实原来的行为其实是合理的 不对的地址就是不对 这会不对的地址怎么等会又对了 感觉只有上游瞎玩dnsmasq之类的玩意才会造成这种问题 是否要其他人为这些DNS灵车爱好者买单？
=> DNS: do not use cache when returned DNS result has errors

features/feature.go
The default `logLevel` is `warning` so normally there are not many people know the features that are deprecating.
This pr does these:
- Changing the feature deprecation warning lo level `warning`: so normally most people can see the warning, and we can have a good use of it.
- Add feature removal warning: This indicate the feature has been removed, and can be use as a "REMOVE BEFORE FLIGHT" tag so we can remove this warning after a long enough period of time.
这个改动是像原来设计/现在这样放在 `features` 里面，还是转移到 `errors` 比较好？
=> Log: Improve feature deprecation/removal logs

proxy/vless/encoding/encoding.go, proxy/vless/encoding/encoding_test.go, proxy/vless/inbound/inbound.go, proxy/vless/validator.go
Made validator an interface and moved its creation out from VLESS constructor to allow custom validators.
It may be the way towards custom validators in Xray, but more importantly it will help people who imports Xray as a library. For example i wanted to implement custom logging and also store users in key-value DB with long term in-memory cache. With this change it will be possible.
=> Allow to inject custom validator in VLESS controller

app/dispatcher/default.go, app/router/command/config.go, app/router/router.go, features/routing/router.go
For #3311
加一个子命令是不太可能了 但是可以选择在log中输出命中的规则
翻了一下代码之后发现一个似乎没人用文档也没写的 `“ruleTag”` 项 不如用起来
现在如果设置了 `“ruleTag”` 在hit中这个rule的时候便会显示这个tag名 用于调试
效果如图
=> Log: show the matching rule tag

app/observatory/burst/healthping.go, common/dice/dice.go
When using burstObservatory I get a panic on the mipsle processor. During the [roll](https://github.com/XTLS/Xray-core/blob/main/app/observatory/burst/healthping.go#L159), "duration" is converted to int, causing overflow on x32 processors. The value may be very small, causing private queries, or negative, causing a panic in rand.Intn.
Version: `Xray 1.8.18 (Xray, Penetrates Everything.) 9e6d7a3c (go1.22.5 linux/mipsle)`
Config burstObservatory:
```json
{
"burstObservatory": {
"subjectSelector": ["proxy"],
"pingConfig": {
"destination": "https://connectivitycheck.gstatic.com/generate_204",
"connectivity": "",
"interval": "30s",
"sampling": 3,
"timeout": "3s"
}
}
}
```
Stdout:
```
panic: invalid argument to Intn
goroutine 35 [running]:
math/rand.(*Rand).Intn(0x21139e0, 0xf46b0400) …
```
=> Fix int overflow on x32 processors causing panic using burstObservatory 

app/dns/dns.go, app/dns/hosts.go, common/errors/feature_errors.go, features/feature.go, infra/conf/transport_internet.go, infra/conf/trojan.go, infra/conf/xray.go, proxy/socks/server.go
接 #3793 
- 此次 pr 稍微修改了两个函数的提示描述，并且升级了 `PrintRemovedFeatureError()` ：此次修改使其在调用时可以正常返回错误从而达成一些遇到停用功能之后自动退出程序的效果，不需要再借助 `errors.New()` （实际上该函数为其封装作为专用用途）。
- 将 `PrintRemovedFeatureError()` 应用到已移除功能上面，提示用户需要修改配置，并且有利于日后的残余代码清理（删除已久的功能）：
- Trojan Flow
- `"security": "xtls"`
- 全局传输设置
~~想给 QUIC 和 DomainSocket 也加上但是没留位置~~
优点是只需在函数信息中填入功能名字即可。
缺点是每次使用这个函数都要引入 features 包，各方面可能不如引入 errors 包方便。
=> Errors: Add PrintRemovedFeatureError & PrintDeprecatedFeatureWarning

transport/internet/browser_dialer/dialer.html
First of all... What. The. Heck.
I can only do so much to try getting the current code up to shape.
- [Strict mode - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)
I really don't know if the browser dialer was designed to work on Internet Explorer, but proper web stream API support don't really exist on that platform. So why didn't the browser dialer have strict mode enabled when this could bring performance gains...
- [var - JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var)
- [let - JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let)
TL;DR, avoid using `var` at all costs. `var` introduces problems of the yesteryear, where `let` declarations are much …
=> Browser Dialer: Change from ES5 to ES6+ for performance

infra/conf/transport_internet.go
It turns out that some panels like to set `"xmux": {"maxConnections": 0, "maxConcurrency": 0}`, and of course that fails now. To make their job easier, let's treat `0` the same as not setting the parameter.
Again, I don't like that xray's defaults are hardcoded all over the place. I would have liked a different default value for Xmux in a future version, but it actually can't be done in practice because everybody just copypastes the defaults from the docs into their own sourcecode (and sometimes changes them silently to their own idea of a good default)
=> Xmux: Value of 0 is treated the same as no value

infra/conf/transport_internet.go, transport/internet/http/dialer.go, transport/internet/http/http_test.go, transport/internet/http/hub.go, transport/internet/splithttp/hub.go
既然我在测试的 Quic 被删了 那只能用 H3 加回来。。
```
"streamSettings": {
"network": "http",
"security": "tls",
"httpSettings": {
"host": ["xray.com"],
"path": "/random/path",
},
"tlsSettings": {
"serverName": "example.com", // Change to your domain.
"alpn": [
"h3"
]
}
},
```
=> Transport: Add HTTP3 to HTTP

infra/conf/transport_internet.go
几年前就想这么干了，这下顺眼多了，新版发布后文档应作出对应修改，只写 `raw` 和 `rawSettings`
=> Transport: Add RAW as an alias of TCP

infra/conf/common.go
fix https://github.com/XTLS/Xray-core/issues/3854
=> 使splithttp可以正常解析以string形式输入的int

app/router/condition.go
Last month the regexp syntax support in UserMatcher was added by https://github.com/XTLS/Xray-core/pull/3799. I've just noticed I made a typo which prevents regular expression matching at all. Sorry for that. This PR makes it work fine.
=> Routing: Fix regexp syntax support in UserMatcher

infra/conf/common.go, infra/conf/freedom.go
https://github.com/XTLS/Xray-core/pull/3855#issuecomment-2387588328
Why not?
=> Refactor: Use struct `Int32Range` widely

common/session/session.go
见 #3904 
mmm似乎在inbound上遇到了类似的问题 这里的问题是content
问题还是老问题 对于一条被mux的连接 多个子请求在内部共享一条ctx
mmm的做法是在mux阶段创建一个深拷贝避免它们相互影响
这里更麻烦一些 因为content是在mux后面的dispatcher才被创建的 没法在mux处理 我也拿不定怎么搞 或许WithCancel另起一个新的ctx? 不是很敢乱动
说回这个issue 本质是多个连接都在尝试往content写入数据 当同时写入的时候遇到竞争就炸了 临时解决办法是加锁 这样好歹不会崩溃 但是并没有解决多个连接共享content的问题 这可能导致预期外的路由或者其他非规定行为
=> Routing: Add mutex for `Attributes` temporarily

infra/conf/transport_internet.go
这样可以改进默认配置下 SplitHTTP 的使用体验，看了下代码，加到配置解析这里最合适，不过 API 可能会绕过这些默认值
看了下代码，splithttpNewRandRangeConfig 的 nil 改为 0 不会有问题
=> XMUX: Change to non-infinity-reuse default values

common/protocol/http/sniff.go, common/session/session.go
之前就看到了setattr那个函数（毕竟调的最多）
其他函数也可能遇到类似情况  补上了
=> Fix: Apply mutex when visiting `Attributes` as well

proxy/wireguard/config.go
fix #3959
白话：system TUN 没做混杂模式支持 压根不能用 只能用 gvisor 如果没有设置的话 刚好又是Linux有权限 会尝试去用 然后炸掉 导致问题
对了 这个不是新版本引入的 旧版本也有问题
=> Wireguard inbound: Do not use system TUN

transport/internet/memory_settings.go, transport/internet/splithttp/dialer.go
**XHTTP 上下行分离时的 XMUX 并不对称**，举个例子，若上下行均未填 XMUX，即均取以下默认值时：
```jsonc
{
"maxConcurrency": "16-32",
"maxConnections": 0,
"cMaxReuseTimes": "64-128",
"cMaxLifetimeMs": 0
}
```
**上下行分别在 range 内 roll 出的确定值是独立、无关的**，比如可能上行 maxConcurrency=16，下行 maxConcurrency=32
**这样随着时间的推移，同一子连接的上下行会更容易被分到上行的第 N 号连接、下行的第 M 号连接，反分析效果更好**
若以 maxConnections 为基础，则会加速随机，因为它是先开满连接数然后 rand 取用，而 maxConcurrency 是遍历数组
所以若以固定值的 maxConcurrency + cMaxReuseTimes + cMaxLifetimeMs 为基础，可能会导致上下行的 XMUX 对称
=> XHTTP client: Enable XMUX for download in U-D-S

app/dns/dnscommon_test.go
Fix prompt from go vet
`dns/dnscommon_test.go:91:14: non-constant format string in call to (*testing.common).Errorf`
=> Test: Fix incorrect output format

app/proxyman/inbound/worker.go, common/net/destination.go
fix #3966
我最开始因为在windows上全改成了127复现不能 因为只发生在使用 uds 的时候 因为 @RPRX  刚好在这里用了 `@xhttp` 的uds 在尝试代理udp的时候会在控制台打印一条access message
```
from tcp: accepted udp:localhost:4000 [direct]
```
这条消息的正确含义是从xxx来了一个请求 xxx是源地址
那uds哪来的源地址 没有 导致网络类型填了一个默认的tcp类型 address更是nil 然后调string 炸了（你想知道它长什么样吗 `:0`）
在这里我把监听的ds文件作为源写入了日志 同时给NetAddr()加了一层nil检查避免以后有类似事故
=> UDS: prevent crash when proxy udp

app/log/log.go, app/observatory/burst/ping.go, app/proxyman/inbound/inbound.go, app/proxyman/outbound/handler.go, common/protocol/user.go, core/config.go, core/xray.go, infra/conf/transport_internet.go, proxy/blackhole/config.go, transport/internet/memory_settings.go
I fix some spelling errors. I am not native speaker, so my version may not be perfect but I hope it is better than the current one.
=> Fix spelling errors

transport/internet/splithttp/dialer.go
**XHTTP 上下行分离 https://github.com/XTLS/Xray-core/pull/3955 要求到达同一 XHTTP 入站的 POST、GET 基于同一 path，否则 XHTTP 入站会拒绝处理**
我看到有群友用 Nginx 改了 path，还有些中间件会 trim prefix，索性放开客户端的限制，反正最终 path 一致就行
=> XHTTP client: Allow different paths in U-D-S

transport/internet/config.pb.go, transport/internet/config.proto, transport/internet/kcp/config.pb.go, transport/internet/kcp/config.proto
I fix some wrong/obscure comments. Hope my version is more understandable.
=> Chore: Fix some comments

infra/conf/transport_internet.go
这件事想了很久怎么设计，最终决定 **直接分享原始 JSON**，~~其实前天突然写了 stream-up 模式就是为了上车~~
上个月我已说过，若要分享数量多、低频的、不断变化的这些参数，反复更新分享链接标准、等待各个 GUI 跟进绝对是灾难
况且这些参数层级、形式多样，设计进分享链接绝对酸爽，~~况且有些客户端根本就不给这些参数写 UI~~
**正好原始 JSON 本身就已经以不冗杂的方式包含了所有信息，没有必要再重新设计一遍**
**若 extra 存在，则整个取代 xhttpSettings，除了 host、path、mode，比如下面生效的是 path-a 和 xmux-b：**
```jsonc
"xhttpSettings": {
"path": "/path-a",
"xmux": {
(xmux-a)
},
"extra": {
"path": "/path-b",
"xmux": {
(xmux-b)
}
}
}
```
~~可能出于安全考虑~~，目前填在 extra 中的 downloadSettings 会被删掉 sockopt，虽然 downloadSettings 还是比上行能分享的内容更多，似乎不太公平，但又不好往外移 extra，~~否则不如不断外移、直接做 Xray JSON 订阅，结果分享链接还是残的~~
分享链接标准已补充 mode 和 extra，并跟进了近期 Xray-core 的改动：https://github.com/XTLS/Xray-core/discussions/716
=> XHTTP config: Add "extra" for sharing extra fields

common/protocol/quic/sniff.go
这个~~copy来的~~QUIC sniffer有很小的概率会slice err 以后找时间研究下 现在没办法就跳过这次嗅探了 至少别崩溃
=> Sniff: Prevent crash on QUIC sniffer panic

app/dns/nameserver_quic_test.go
My ISP blocks `*.adguard.com` so DNS over QUIC test results look like this:
```
$ go test github.com/xtls/xray-core/app/dns
...
--- FAIL: TestQUICNameServer (2.00s)
panic: context deadline exceeded [recovered]
panic: context deadline exceeded
goroutine 356 [running]:
testing.tRunner.func1.2({0xb931c0, 0x129f360})
/usr/local/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1634 +0x377
panic({0xb931c0?, 0x129f360?})
/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/xtls/xray-core/common.Must(...)
/Xray-core/common/common.go:21
github.com/xtls/xray-core/app/dns_test.TestQUICNameServer(0xc0000eed00)
/Xray-core/app/dns/nameserver_quic_test.go:27 +0x2ca
testing.tRunner(0xc0000eed00, 0xc89b80)
/usr/local/go/src/testing/testing.go:1689 …
```
=> Test: Change address for DNS over QUIC tests

.github/docker/Dockerfile
Docker volume /etc/xray only contain s config.json in default condition. Changing to confdir could provide support to both single file mode and multi-file mode.
=> Update Dockerfile to Use Multiple Config Files

proxy/vmess/validator.go, transport/internet/tls/config_other.go
The new pr for https://github.com/XTLS/Xray-core/pull/4005.
I wrote a tool to detect this, but it has a high false positive rate. 
I checked it one by one and I am sure there are only two such examples in the current code...
=> Chore: Use a more direct and less error-prone return value

infra/conf/dns_test.go
As far as I can see the code in the `init()` function in `infra/conf/dns_test.go` does some preparation but the file created is never used. So I removed the code.
=> Chore: Drop dead code in test

proxy/wireguard/tun_linux.go
Fix #2817
问题很简单 Tun的时候默认使用的1023路由表只有一个 再多会冲突 这里稍微修改了一下 从10230开始依次递增分配不同的路由表号 这样多次创建tun接口的时候就不会冲突了
=> WireGuard kernelTun: Fix multi-outbounds not work

infra/conf/dns_test.go, infra/conf/router_test.go
Improvements:
- drop `init()` functions, use more straightforward code
- don't write `geoip.dat` into the project directory*
- don't write `geoip.dat` twice
\*`geoip.dat` is written into the project directory if you have that file in `./resources` only:
- `init()` function in `dns_test.go` sets environment variable `xray.location.asset` to `os.Getwd()` i.e. to `infra/conf`
- `init()` function in `router_test.go` writes `geoip.dat` to `platform.GetAssetLocation()` i.e. to `infra/conf`
=> Chore: Refactor infra/conf.TestToCidrList()

infra/conf/common.go, infra/conf/xray.go
Because Mr. R has appended new "extra" field to sharing protocol, it's time to use the original config of Xray-core when parsing share links.
This commit contains two modifications.
1. append "Name" field to "OutboundDetourConfig".
2. support marshaling "Address".
Maybe we should make more changes in the future, but it is enough currently for VLESS sharing protocol.
=> Config: Correctly marshal `Address` to JSON

proxy/wireguard/server.go
Fix #3948 #4025 
我本来以为是设计缺陷，结果这竟然是故意的，wg入站在入站级别共享一系列session参数(s.info) 这些参数对于每个请求都应该是独立的 多个入站互相操作这些参数导致目标可能被不正确重置 暂时没看懂为什么这么做
=> WireGuard inbound: Fix leaking session information between requests

common/log/logger_test.go
The temporary file created by `common/log.TestFileLogger()` is currently not deleted.
=> Test: Delete temporary file afterwards

transport/internet/http/config.go, transport/internet/http/dialer.go
http类传输的一堆work around 类似之前的WS和httpupgrade
今天研究这个过CF的时候发现的 如果问能不能过的话 是的 这个传输稍作修改就能透传CF
=> HTTP transport: Use dest as Host if not set

app/router/condition_geoip_test.go, app/router/condition_test.go
I refactored `geoip.dat` & `geosite.dat` reading in `app/router` tests.
Improvements:
- drop `init()` functions, use more straightforward code
- don't copy `geoip.dat` & `geosite.dat`
=> Chore: Refactor tests in app/router

testing/scenarios/common.go, testing/scenarios/main_test.go
The temporary directory created by `testing/scenarios.genTestBinaryPath()` is currently not deleted. Note that `TestMain()` is a [special function that is executed before any tests in a package](https://pkg.go.dev/testing#hdr-Main).
=> Test: Remove temporary directory afterwards

proxy/vless/inbound/inbound.go
There is a line that appeared in my logs that is quite ambiguous. Only after reading the source code could I understand what that meant. Fixing that to make the reason for the Warn clearer
=> Chore: Improved log messaging

infra/conf/transport_internet.go, transport/internet/splithttp/browser_client.go, transport/internet/splithttp/client.go, transport/internet/splithttp/dialer.go, transport/internet/splithttp/hub.go
https://github.com/XTLS/Xray-core/pull/3994#issuecomment-2497920598 让我们补上 XHTTP 近期最后一大块拼图：
现有的 HTTP 传输层使用“**一条子连接**”承载一条被代理请求，即没有任何上下行逻辑分离。**但它一直以来存在一个没有 header padding 的大问题，即请求头和响应头在 TLS 上会表现出固定的长度特征。** 加 header padding 不难，但穿墙协议的安全更新不应默认兼容旧版，否则会被旧版客户端所拖累。此外 HTTP 传输层与代理协议的名称相撞，亦没有 XHTTP 的 XMUX 等功能。
**所以，最佳解决方案是将 HTTP transport with header padding 作为 stream-one 模式并入 XHTTP 传输层，这样一来也有了 XMUX 等功能而无需维护两份代码。** XHTTP 服务端会检查客户端发来的 x_padding 是否符合所配置的范围（有默认值），以确保不默认兼容原 HTTP 传输层。虽然你也可以将 xPaddingBytes 设为 -1 以兼容原 HTTP 传输层，但不建议，也没有必要这样做。
就像 [stream-up](https://github.com/XTLS/Xray-core/pull/3994) 模式，**stream-one** 模式也默认有 [gRPC header](https://github.com/XTLS/Xray-core/pull/4042) 伪装，据称也可以过 CF H2。**此外，客户端发 gRPC header 伪装时，这个 PR 补上了服务端回应 gRPC header 伪装。** 然而 CDN 可能对 gRPC 有流量限制，所以更建议用 stream-up 仅上行。
所以 …
=> XHTTP: Add "stream-one" mode for client & server

app/proxyman/inbound/inbound.go
[XHTTP](https://github.com/XTLS/Xray-core/discussions/4113) 的 H2 & H3 自带 XMUX，这个 PR 复用了 Vision 通知 Mux.Cool 禁 TCP 的机制，从而防止了双层 Mux，~~至于 H1，它不重要~~
~~底层传输那里 listen 调来调去的太绕了，终于又一次理清后发现加这里最合适~~，**v25 争取把各种 interface 和 register 清掉**
=> XHTTP server: Forbid Mux.Cool except pure XUDP

common/reflect/marshal_test.go, infra/conf/transport_internet.go, infra/conf/xray_test.go, transport/internet/httpupgrade/dialer.go, transport/internet/splithttp/dialer.go, transport/internet/websocket/config.go, transport/internet/websocket/dialer.go
XHTTP, WS, HU 都有单独的 `host` 参数，没有必要允许 `headers` 里填 "host"，[~~GUI 也不会把它填 `headers` 里~~](https://github.com/XTLS/Xray-core/pull/4142#issuecomment-2531581316)，索性禁了
客户端未设置 `host` 时本来自动取 `address`，但若 TLS 或 REALITY 存在，显然取 `address` 不妥，[应当取 `serverName`](https://github.com/XTLS/Xray-core/pull/4142#issuecomment-2532953355)
**客户端新的优先级顺序：`host` > `serverName` > `address`；服务端 `host` 是校验，没事别设，不会自动取 `serverName`**
=> XHTTP, WS, HU: Forbid "host" in `headers`, read `serverName` instead

app/dispatcher/default.go, app/dns/nameserver.go, app/dns/nameserver_fakedns.go, app/observatory/burst/burstobserver.go, app/observatory/burst/healthping.go, app/observatory/burst/ping.go, app/observatory/observer.go, app/router/balancing.go, app/router/strategy_leastload.go, app/router/strategy_leastping.go, app/router/strategy_random.go, core/xray.go, infra/conf/xray.go, proxy/dns/dns.go, transport/internet/tagged/tagged.go, transport/internet/tagged/taggedimpl/impl.go
RequireFeatures() must be called at init.
It should fix memory leak at balancers, observatory and fakedns. Need some testing to confirm it is working as expected.
=> Core: Fix memory leaks with RequireFeatures()

app/dns/nameserver_doh.go, app/dns/nameserver_quic.go
好像使用doq的人比较少一直没人提这个问题，对go不是很熟悉不知道符不符合要求，直接把隔壁的 [pr](https://github.com/v2fly/v2ray-core/pull/3024) 搬过来了，重新编译之后阿里的doq能正常使用了。
=> DNS: Always use a DNS Message ID of 0 for DoH and DoQ

app/dispatcher/default.go, app/dns/nameserver.go, app/observatory/command/command.go, app/proxyman/command/command.go, app/router/balancing.go, app/router/command/command.go, app/router/strategy_leastload.go, app/router/strategy_leastping.go, app/router/strategy_random.go, core/xray.go, core/xray_test.go, proxy/dns/dns.go
- Turns out we already support async DI resolution regardless of feature ordering
Previous code contain a race condition causing some resolution is lost
- Note that the new mutex cover s.pendingResolutions and s.features
but must not cover callbackResolution() due to deadlock
- Refactor some method names and simplify code
=> Core: Add mutex to injection resolution

.github/workflows/release-win7.yml, .github/workflows/release.yml, .github/workflows/test.yml, common/reflect/marshal.go, core/config.go, go.mod
见 https://github.com/XTLS/Xray-core/pull/4192#issuecomment-2558491444
~~该 pr 包含移除使用 Go 1.21.4 编译 win7 版本的更改，应用该 pr 后，自动构建过程不会再产生 `win7-32` 及 `win7-64` 两组二进制。同时在 Github Actions 中构建时使用的 Go 版本取决于 `go.mod` （和之前一致）。~~
~~该 pr 并非 #3530 的完全还原，`patch-assetname` 暂时被保留（可用于其它用途）。~~
~~**建议仅在决定移除使用 Go 1.21.4 提供对 Windows 7 的支持时合并**~~
如果计划用打了 win7 支持补丁的 Go 在 Actions 进行编译，大概需要：一个经过修改的 Go 库，一个修改过的 setup-go，以及单独准备的 actions 文件。~~说不定会出现在 actions 里面先 build go 再用 build 出来的 go 编译特殊版本的事~~
=> Build: Use patched newer Go version to build Windows 7 assets

infra/conf/freedom.go
fix a typo in noise delay parsing
that always set DelayMin to 0
and thus udp noise delay never executed
https://github.com/XTLS/Xray-core/blob/main/proxy/freedom/freedom.go#L422
=> Freedom: Fix noises delay

transport/internet/splithttp/client.go, transport/internet/splithttp/config.go, transport/internet/splithttp/dialer.go, transport/internet/splithttp/hub.go
最近对 [XHTTP](https://github.com/XTLS/Xray-core/discussions/4113) 进行了“换网测试”，**发现 H2 仍存在切换网络后“断流”的问题**（只能等保活检查），而 H3 有一定概率不会断，应该是连接迁移了。尚未研究“多少秒不活跃触发保活检查”的对象是否包含“未响应”，时间是否就是 `hKeepAlivePeriod`。
所以这个 PR 继承了 https://github.com/XTLS/Xray-core/pull/4163 未竟的事业，重新引入了 https://github.com/XTLS/Xray-core/commit/51769fdde1ca663dcb08d942618e480bee13109f ：**任一 HTTP 请求返回 err 就不再分配新请求。**
（context.WithoutCancel(ctx) 确保了不是客户端引发的 err，此前 stream-up 上行没加它，再加上服务端迟迟未响应，疯狂报错）
由于 stream-up 上行旧服务端迟迟未响应、导致最后返回了 err，这个 PR 类似 [REALITY](https://github.com/XTLS/REALITY) 会把客户端版本发给服务端，**所以新服务端会向新客户端及时响应 200**，这解决了 stream-up 上行状态码为 400/499、被 CDN 掐断 https://github.com/XTLS/Xray-core/discussions/4113#discussioncomment-11682833 的问题。
还有 https://github.com/XTLS/Xray-core/commit/836e84b8510a9478bc00dd8690cb71a51a607d11 我不确定要不要引入，似乎 …
=> XHTTP XMUX: Abandon `client` if `client.Do(req)` failed

proxy/freedom/freedom.go
之前 @yuhan6665 修改了freedom让它不要在使用tls执行 rawcopy 方法是尝试将conn断言为tls.Conn 成功则跳过 但是从某个更新之后默认utls导致这里变成了 tls.UConn 致使断言失败
=> Freedom: Don't use rawConn copy when using utls

proxy/socks/server.go
There's an annoying (and scary) log when socks inbound received a connection that immediately closes (e.g. v2rayN probes socks port to see if the core is ready):
```
[Warning] [1650329060] app/proxyman/inbound: connection ends > proxy/http: failed to read http request > malformed HTTP request "\x00"
```
Recognize this case, print a correctly worded Debug level log instead of the Warning with scary message.
=> Mixed inbound: Handle immediately closing connection gracefully

transport/internet/browser_dialer/dialer.go, transport/internet/browser_dialer/dialer.html, transport/internet/splithttp/browser_client.go, transport/internet/splithttp/config.go, transport/internet/splithttp/dialer.go, transport/internet/splithttp/hub.go
Move the padding into `Referer` header, to not bloat the reverse proxy access log.
From browser, the path part of `Referer` header can be controlled with `fetch`:
```javascript
fetch("https://server.example.com/some_path", {referrer: "/?x_padding=000", referrerPolicy: "unsafe-url"})
```
The actual sent `Referer` header value would be `http://<xray.browser.dialer>/?x_padding=000`, and it won't trigger CORS preflight, even if the URL is long (no 128 length limit of ["safelisted headers"](https://fetch.spec.whatwg.org/#cors-safelisted-request-header)).
Therefore it's fully compatible with browser as dialer without overhead. The only downside would be some browsers may strip the path under privacy-protection mode (I see Firefox doing that, but it can be disabled by user for specific sites).
=> XHTTP client: Move `x_padding` into `Referer` header

app/dns/nameserver.go, app/dns/nameserver_local.go, app/dns/nameserver_local_test.go
#4302
我也不知道为什么当初没实现 或许是有原因的 可能需要考古
=> DNS: Implement queryStrategy for "localhost"

app/proxyman/inbound/worker.go
close #4324 
之前因为UDS的source留空会导致panic 所以写了具体的 uds 地址作为占位符
但是UDS监听不一定代表源地址是无效的 当时没有考虑到 源地址可能被传输协议专有的方法比如从 `X-Forwarded-For` 中读取出来 这种情况下源地址是有效的 所以稍微做一下校验
至于issue里有的情况没法复现 因为各入站实现不同 有的是从 conn 中读取源地址 这种可以正常读到 有的是从 ctx 读取 填入uds作为占位的情况只填到了 ctx 里面
=> UDS: Keep valid source addr

proxy/proxy.go, proxy/vless/encoding/addons.go, proxy/vless/encoding/encoding.go, proxy/vless/inbound/inbound.go, proxy/vless/outbound/outbound.go
For each connection, xtls need 4 flags for uplink/downlink reader/writer to decide when it switch to direct copy.
In the past, there were only one for read and one for write. If service has xtls inbound and xtls outbound, the two flags may be corrupted by signal from different directions.
=> XTLS Vision: Use separate uplink/downlink flag for direct copy

main/commands/all/curve25519.go
This transformation was originally added in https://github.com/XTLS/Xray-core/pull/1747.
And then https://github.com/XTLS/Xray-core/pull/2794 changed it to `127 | 64`.
But `x & (127 | 64)` is not the same as `(x & 127) | 64`. For example:
`0 & (127 | 64) = 0`
`(0 & 127) | 64 = 64`
in main:
```sh
$ ./xray x25519 -i AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Private key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Public key: L-V9o0fNYkMVKNqsX7spBzD_9oSvxM_C7ZCZX1jLO3Q
$ ./xray x25519 -i AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEA
Private key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEA
Public key: L-V9o0fNYkMVKNqsX7spBzD_9oSvxM_C7ZCZX1jLO3Q
```
in this PR:
```sh
$ ./xray x25519 -i AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Private key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEA
Public …
```
=> Commands: Fix ambiguous printing of private x25519 key

.github/workflows/hourly-prepare.yml, .github/workflows/scheduled-assets-update.yml
上游 Loyalsoldier/v2ray-rules-dat 目前每天定时 UTC 22:00 更新一次，不会和 v2fly/domain-list-community 一样随时都可能更新
=> Workflows: Reduce Geodata update frequency

.github/workflows/scheduled-assets-update.yml
现在应该可以正常手动触发 assets 更新了，比如 geodata
应该可以解决莫名其妙的 cache 清空导致其它依赖 actions 失败的问题
应用 pr 后需要在 Actions 页面左侧选择对应 action，然后右侧可以手动 Run workflow
=> Workflows: Fix Actions' manual dispatch for assets update

app/proxyman/inbound/worker.go, common/net/destination.go, transport/internet/system_listener.go
=> UDS: Make all remote addr 0.0.0.0

proxy/http/client.go, proxy/http/server.go, proxy/proxy.go, proxy/socks/client.go, proxy/socks/server.go, proxy/vless/encoding/encoding.go
- In 03131c72dbbfc13ba4ce8e1f9f65f43f3dda7372 new flags were added for uplink/downlink, but that was not suffcient
- Now that the traffic state contains all possible info
- Each inbound and outbound is responsible to set their own CanSpliceCopy flag. Note that this also open up more splice usage. E.g. socks in -> freedom out
- Fixes https://github.com/XTLS/Xray-core/issues/4033
=> XTLS: More separate uplink/downlink flags for splice copy

proxy/proxy.go, transport/internet/system_listener.go
=> UDS: Use UnixListenerWrapper & UnixConnWrapper

app/proxyman/outbound/handler.go, infra/conf/xray.go
In case when there are few IP-addresses on the server, it would be good for outbound to have behavior when it resolves origin IP address and then sends packets through it. Before the choice was delegated to OS.
This behavior can be used with explicit specification in the outbound config:
`{"outbounds":[
{
"protocol":"freedom",
"tag":"DIRECT",
"sendThrough": "origin"
}
}`
=> Outbound: Add outbound sendThrough origin behavior 

infra/vprotogen/main.go, main/commands/all/convert/json.go, main/commands/all/convert/protobuf.go
新版go要求你调用 printf 的时候起码得带一个格式化字符串 不能纯当 print 用 出于向下兼容它不会编译失败 但是会在test中返回错误
=> Chore: Fix tests

transport/internet/splithttp/hub.go, transport/internet/splithttp/splithttp_test.go
Go 1.24 has add the native unsecured http2 support: https://redirect.github.com/golang/go/issues/67816. And the [x/net/http2/h2c package is going to be deprecated](https://redirect.github.com/golang/go/issues/72039). We may be able to replace the x/net/http2/h2c package and use native h2c support instead.
=> Chore: Use native h2c support

README.md
**Remnawave** is a powerful proxy managment tool, built on top of [Xray-core](https://github.com/XTLS/Xray-core), with a focus on security, simplicity and ease of use.
The developer places a strong emphasis on security, addressing the concerns we discussed earlier, and is highly responsive to all inquiries.  
Although the panel was created relatively recently, it is already being used in production environments by many users.
=> README.md: Add Remnawave to Web Panels

app/stats/online_map.go
Fix #4512
字面意思 list[ip] 这个操作也应该被lock保护
=> API: Fix data race in online ipList

app/dns/dnscommon.go, app/dns/dnscommon_test.go, app/dns/nameserver_udp.go
RT 如果DNS消息回复被截断则再次发送带EDNS的请求并把大小扩展到1350
=> DNS: Retry with EDNS0 when response is truncated 

app/dns/dns.go, app/dns/dns_test.go, app/dns/dnscommon.go, app/dns/nameserver.go, app/dns/nameserver_doh.go, app/dns/nameserver_doh_test.go, app/dns/nameserver_fakedns.go, app/dns/nameserver_local.go, app/dns/nameserver_local_test.go, app/dns/nameserver_quic.go, app/dns/nameserver_quic_test.go, app/dns/nameserver_tcp.go, app/dns/nameserver_tcp_test.go, app/dns/nameserver_udp.go, app/router/router_test.go, features/dns/client.go, features/dns/localdns/client.go, features/routing/dns/context.go, proxy/dns/dns.go, proxy/freedom/freedom.go, proxy/wireguard/bind.go, proxy/wireguard/client.go, testing/mocks/dns.go, transport/internet/dialer.go
响应给客户端的TTL不应是魔法值600
此PR能做到：
- FakeDNS = 1
- Hosts = 10
- LocalDNS = 600 （若觉得不合适可改成60）
- 其它遵循上游DNS，体现出当前Xray管理的缓存有效期
Closes https://github.com/XTLS/Xray-core/issues/4527
=> DNS: Support returning upstream TTL to clients

proxy/http/server.go
fix #4545 
将所有1xx response读取后直接转发给客户端 不再给其余部分处理
=> HTTP inbound: Directly forward plain HTTP 1xx response header

app/dns/nameserver_doh.go, app/dns/nameserver_quic.go, app/dns/nameserver_tcp.go, app/dns/nameserver_udp.go
First, I have to thank @Fangliding for his guidance on https://github.com/XTLS/Xray-core/pull/4558#issuecomment-2759007356.
I mistakenly think that the problem is related to log, but in fact log is just log and has nothing to do with performance.
in https://github.com/XTLS/Xray-core/pull/3784 @Fangliding change the original code `err != errRecordNotFound` to `err == nil || err == dns_feature.ErrEmptyResponse` To be more accurate.
but in android some apps send thousands of requests in a matter of seconds, that return `NXDOMAIN`.
This causes performance to drop drastically, and many people have complained about this.
So I also added `NXDOMAIN` to the modes that should use `cache`.
=> DNS: Use cache for NXDOMAIN (rcode 3)

infra/conf/wireguard.go, infra/conf/xray.go, proxy/wireguard/gvisortun/tun.go, proxy/wireguard/server_test.go
This pull request:
1. Properly wraps config building errors with context-rich error messages
2. Adds validation for empty WireGuard keys with clear error messages
3. Implements proper resource cleanup in WireGuard TUN device with a sync.Once to prevent double-close issues leading to panic
4. Adds test case to verify WireGuard server initialization handles errors gracefully without panicking
Overall, this leads to much better user experience in case of misconfiguration
=> WireGuard: Improve config error handling; Prevent panic in case of errors during server initialization

transport/internet/sockopt_darwin.go
fix https://github.com/XTLS/Xray-core/issues/4007
=> Sockopt: Fix Darwin (macOS, iOS...) UDP `interface` bind

transport/internet/sockopt_darwin.go, transport/internet/sockopt_windows.go
=> Sockopt: Add Windows `V6Only`

infra/conf/cfgcommon/duration/duration.go, infra/conf/common.go, infra/conf/dns.go, infra/conf/fakedns.go
Added `MarshalJSON` for the below structs
- `FakeDNSConfig`
- `HostAddress`
- `PortRange`
Rewritten `MarshalJSON` for
- `PortList`
Also adds comments and prefers pointer receivers.
=> Config: Implement missing MarshalJSON for structs having custom UnmarshalJSON

app/proxyman/outbound/handler.go, proxy/wireguard/client.go, transport/internet/system_dialer.go
Commit https://github.com/Cl-He-O/Xray-core/commit/690d76fb9ea87fcb18ee50a6d938df99de1c4117 fix the issue described in https://github.com/XTLS/Xray-core/issues/4613.
Commit https://github.com/Cl-He-O/Xray-core/commit/115fa4449b36e81751637600d9254ac11c21d500 fix issue that dialer controllers are not called, introduced by https://github.com/XTLS/Xray-core/commit/8284a0ef8f1ee3774982cb6e53f53848401fa3a5. Dialer controllers are used in an android client to protect socket from looping back.
=> Fix issues related to android client

app/dispatcher/default.go, common/protocol/quic/sniff.go
* https://github.com/XTLS/Xray-core/pull/4642#issuecomment-2834831384
=> QUIC sniffer: Optimize the code

transport/internet/dialer.go
i fixed these bugs with "happy eyeballs" PR, but @RPRX  said to seperate the PRs.
so, after this PR merged, i open new PR for "happy eyeballs".
///
1. You forgot to return error for `ForceIP` mode when no ip is found, and wrongly, `ForceIP` mode was no different from `useIP` mode.(for sockopt-domainStrategy)
[also, when `forceIP` is set, it shouldn't use `AsIs` in any situation (when `dnsClient == nil`) and should return error instead]
3. you forgot to return error when user misspelled the outbound-tag-name in `dialerProxy`.(wrongly, you ignore `dialerProxy` in such a situation and the user mistakenly thought everything was working properly).
=> Sockopt: Fix some domainStrategy & dialerProxy bugs

app/dns/hosts.go
currently we cannot set `[]` for a domain in hosts.(the code return error)
but we may want to return no IP (EmptyResponse) for a domain, for example return no IP for ads-domains to block them:
```
"dns":{
"hosts": {
"geosite:category-ads-all": []
}
}
```
so i extend ability to set `[]` or `""` for a domain when we want no IP to return for a domain (EmptyResponse)
suppose we want to return "216.239.38.120" for "youtube.com" but return "216.239.38.119" for other google sites, so we set:
```
"dns":{
"hosts": {
"youtube.com": ["216.239.38.120"],
"geosite:google": ["216.239.38.119"]
}
}
```
But the code accumulates the results, and we will eventually have:
`"youtube.com": ["216.239.38.120","216.239.38.119"]`
so we don't get the desired result.
**so we should not accumulate matched-results, We …
=> DNS: Extend `hosts` Abilities

app/dns/hosts.go
Unmarshalling json in golang will not respect order.
So, sorting `h.matchers.Match(domain)` in https://github.com/XTLS/Xray-core/pull/4673 is useless and the order of the results is still messed up, Because `json.Unmarshal` messed up the order of domains at the very beginning.
So, I temporarily reverted this to the previous state (appending matched-results).
///
I need to change `json.Unmarshal` for hosts to completely fix this issue.
=> DNS-Hosts: appending matched-results again

.github/workflows/release-win7.yml, .github/workflows/release.yml, .github/workflows/scheduled-assets-update.yml, .github/workflows/test.yml
test和build流程依赖geodat，但无法确保它们存在，只是简单的从cache恢复
因为这些资源依赖`scheduled-assets-update.yml`定时下载，有时fork或开新分支时它没能被触发就会导致如下错误
=> Workflows: Ensure Geodat exists

app/dispatcher/default.go, app/dns/dns.go, features/dns/client.go
during reading dispatcher codes, I encountered a strange code:
https://github.com/XTLS/Xray-core/blob/72170d8b6be0d83af1624f6d31b81cf73f1a189c/app/dispatcher/default.go#L410-L421
First, **fortunately** this code was not executed at all, because `ob.Target.String()` has prefix("tcp:"/"udp:") and `hosts.LookupHosts(ob.Target.String())` always returned `nil` and as a result `proxied` was always `nil` and the code was not executed at all !!!
Second, this code should not be executed at all, because the logic of this code is **completely wrong**, and we should not use `built-in-dns-hosts` to replace the `ob.Target` and change the destination, because suppose we are in client-side and we want to use `built-in-dns‍` only in client-side, and destination is used in server-side, so we should not …
=> Removing code that was not being executed and should not be executed.

app/dispatcher/default.go
during reading sniffer code, i found two bugs and fixed them:
https://github.com/XTLS/Xray-core/blob/72170d8b6be0d83af1624f6d31b81cf73f1a189c/app/dispatcher/default.go#L376
if ` cacheErr != buf.ErrReadTimeout` (cacheDeadline not exceed) and `payload.IsEmpty()`, The code gets stuck in infinite loop, and CPU usage reaches 100%, and the app crashes !
(also if `cacheErr == nil` and `payload` doesn't change and `ErrProtoNeedMoreData`, the same thing happens)
**This bug is probably the main reason for https://github.com/XTLS/Xray-core/issues/3914.**
After reviewing the code, I realized that `"destOverride": ["fakedns+others"]` is no different from `"destOverride": ["fakedns"]`, That means `"destOverride": ["fakedns+others"]` behaves exactly like `"destOverride": ["fakedns"]`.
I also tested this …
=> Sniffer: Fix potential infinite loop

common/protocol/quic/sniff.go, common/protocol/quic/sniff_test.go
=> QUIC sniffer: Fix potential slice panic

core/xray.go
So in this contribution I did a small change and exported the running bool. code follows
```go
func (server *Instance) IsRunning() bool {
return server.running
}
```
But why ? right?
the reason behind it is I wanted to implement this feature in [libXray](https://github.com/XTLS/libXray) but when I went on I saw `running` wasnt like exported and I cannot access that. So to have a api to check current core state in libXray we need it. For reference another xray wrapper like to mention [AndroidLibXrayLite](https://github.com/2dust/AndroidLibXrayLite) has the same feature to get core state. So choosed to have it also in libXray.
=> Core: Export the running bool

infra/conf/xray.go
The documentation description about ‍`fakedns+others` is completely wrong: https://github.com/XTLS/Xray-core/pull/4733#issuecomment-2888134773.
and even if we fix it, it will just be an redundant option.
So I agree with  @yuhan6665  and  @Fangliding  and i did [this](https://github.com/XTLS/Xray-core/pull/4726#issuecomment-2886494540).
=> Sniffer-destOverride: Remove `fakedns+others` option

testing/scenarios/command_test.go
错误是由 PR #4723 引入的
然后 PR #4789 是输出diff，以供后续定位问题
现在本PR根据抓到的日志来修复此错误
目前只抓到一条日志：
看起来像是protobuf序列化结果有时会顺序不一致导致测试不通过
```log
=== RUN   TestCommanderListHandlers
Xray 25.5.16 (Xray, Penetrates Everything.) Custom (go1.24.4 darwin/arm64)
A unified platform for anti-censorship.
2025/06/07 13:22:28.581087 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:49289
2025/06/07 13:22:28.581153 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:49290
2025/06/07 13:22:28.581157 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:49289
2025/06/07 13:22:28.581159 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:49290
Warning: 7 13:22:28.581364 [Warning] core: Xray 25.5.16 started
2025/06/07 13:22:30.575509 [Debug] [2378785008] proxy/dokodemo: processing connection …
```
=> Tests: Real fix for TestCommanderListHandlers

.github/docker/Dockerfile, .github/docker/Dockerfile.usa
解决`/usr/local/share/xray`目录缺少x权限，导致geodata无法加载的问题
=> Docker: Fix geodata directory permissions issue

proxy/trojan/validator.go, proxy/vless/validator.go
Fixes #3644. 
In the VLESS and Trojan protocols, GetByEmail did not account for the fact that emails are stored in lowercase, so the `api inbounduser` could not find a user if the email was written using uppercase letters.
=> API: Fix issue with inbounduser not finding emails with uppercase letters

infra/conf/dns_proxy.go, proxy/dns/dns.go
close #4819
Windows上的nslookup也会卡(因为ptr查询)
=> DNS: Add new nonIPQuery "reject"

main/commands/all/tls/ping.go, transport/internet/tls/config.go
为 xray tls ping 新增密钥交换算法显示 方便查看一个地址是否支持后量子 配合reality
```
./xray tls ping cloudflare.com
Tls ping:  cloudflare.com
Using IP:  104.16.132.229
-------------------
Pinging without SNI
Handshake succeeded
TLS Version: TLS 1.3
Post-Quantum key exchange: true (X25519MLKEM768)
Allowed domains:  [cloudflare.com *.amp.cloudflare.com *.cloudflare.com *.dns.cloudflare.com *.staging.cloudflare.com]
-------------------
Pinging with SNI
handshake succeeded
TLS Version: TLS 1.3
Post-Quantum key exchange: true (X25519MLKEM768)
Allowed domains:  [cloudflare.com *.amp.cloudflare.com *.cloudflare.com *.dns.cloudflare.com *.staging.cloudflare.com]
Tls ping finished
```
=> Commands: Display Post-Quantum key exchange in `tls ping`

app/stats/command/command.go
currently when we request a stat and is not available, we get Unknown in return, this is not right and we should get NotFound status.
=> Stats API: Return status "not found" instead of "unknown"

.github/workflows/docker.yml
- 中间产物用 digest 而非 -usa 这种临时标签来标记，这样不污染 registry，专治 @RPRX 强迫症
- pre-release 时不打 latest 标签，只有版本号
- pre-release 转为 latest 时自动打 latest
- 支持手动运行
---
=> Workflows: Cleaner Docker builds, support for manual exec and pre-release

proxy/freedom/freedom.go
the problem https://github.com/XTLS/Xray-core/issues/4800#issue-3132409092 is because after browser sending UDP-data(quic initial packet) the packet correctly reaches to the final-target but the response-data does not reach to the browser, this problem happen when target-address is domain, let's explain why:
**code-A (freedom.go > ReadMultiBuffer):**
https://github.com/XTLS/Xray-core/blob/fbae89d017aee5947598d0a82945b316fdc688ab/proxy/freedom/freedom.go#L309-L313
**code-B (udp/dispatcher.go > handleInput):**
https://github.com/XTLS/Xray-core/blob/fbae89d017aee5947598d0a82945b316fdc688ab/transport/internet/udp/dispatcher.go#L135-L138
**code-C (socks/server.go):**
https://github.com/XTLS/Xray-core/blob/fbae89d017aee5947598d0a82945b316fdc688ab/proxy/socks/server.go#L237-L243
suppose browser …
=> Freedom: Fix UDP reply mismatch-address

common/mux/client.go, common/mux/client_test.go, common/mux/server.go, common/mux/session.go, common/mux/session_test.go
https://github.com/XTLS/Xray-core/blob/cb1afb33e68c56bf4510ad658ab86a0468b8c36c/common/mux/client.go#L291-L297
**if this function run concurrent from two goroutine, some problems may arise, let explain why:**
suppose `m.strategy.MaxConcurrency` is set to 4, and currently we have 3 sessions for `m.sessionManager`.
suppose goroutine-A and goroutine-B run this function concurrency, because we have 3 sessions and `MaxCuncurrency` is set to 4, `m.IsFull()` is `false` for both goroutine, so both goroutine will run `sm.Allocate()`.
although `sessionManager` has it's own Lock, but it does not help in this situation, and `sm.Allocate()`  create a new session for each goroutine. 
**so after running this two goroutine two new sessions created and the number of sessions reach to 5, but …
=> MUX: Refine and Fix some occasional problems

app/reverse/config.go, app/reverse/portal.go, common/mux/client.go
when a portal-worker is draining, heartbeat-reader/writer is immediately closed, this causes some problems, let explain why:
suppose we only have one active portal-worker and it starts draining.
also support the only sub-connection(session) of this worker is heartbeat-sub-connection and it has no client-sub-connection.
after heartbeat-sub-connection is closed, the number of sub-connection(session) of the worker reaches 0,
worker check every 16 seconds if there is no session(sub-connection), It closes itself.
**So there is a chance that the worker will be closed after heartbeat-sub-connection is closed and before the new worker arrives from bridge-side.**
**So during this time, until a new worker is created and arrives from bridge-side, our connection with bridge-side will be completely …
=> Reverse: portal-worker should not be closed before making sure there is at least one other active worker

transport/internet/udp/dispatcher.go
=> UDP: Fix removeRay will close a connEntry that not belongs to it

transport/internet/reality/reality.go
难道以前一直没人看这个输出吗 我看的时候服务端输出true客户端输出false一头雾水(
selectedGroup 不是服务端选择的group(不同于selected alpn 它确实是服务端给出的alpn协商结果) 这个东西是HelloRetryRequest里用的 服务端想用这个keyshare重新进行协商 而不是说本次握手协商出的keyshare 它直接被编码在 server hello 的keyshare.group 里 所以要像我之前 tls ping 那样反射出来(
=> REALITY client: Fix log when printing "is using X25519MLKEM768..."

transport/internet/sockopt_linux.go, transport/internet/system_dialer.go, transport/internet/system_listener.go
from #4927
重写了一下 tcp keepalive 的逻辑 删除了 sockopt_linux 里的操作 移到了 listener/dialer 中 这样可以跨平台
现在的逻辑
客户端 打开 TCP 连接使用和 Chrome 相同的 idle 和 interval (45秒) sockopt中两个数字任一为负则禁用 为正则覆盖默认值
服务端 监听默认不启用 任一大于 0 的 idle 或 interval 启用keepalive 并把相关数字设置成对应值 如果没设置 则为系统默认(而不是golang默认)
由于两个参数任一大于0启用和任一小于0禁用 一个正一个负会逻辑错误 如果发生这样的事直接返回错误
=> Inbounds & Outbounds: TCP KeepAlive better default value

main/commands/all/api/api.go, main/commands/all/api/inbound_user_add.go, main/commands/all/api/inbound_user_remove.go
这个 PR 添加 adu 和 rmu 两个管理 inbound 用户的命令行 API。支持 vless, vmess, trojan, ss 四种协议。  
主要给个人使用，机场有自己的面板应该不需要这个功能。  
```bash
$ ./xray help api adu
usage: xray api adu [--server=127.0.0.1:8080] <c1.json> [c2.json]...
Add users to inbounds.
Arguments:
-s, -server
The API server address. Default 127.0.0.1:8080
-t, -timeout
Timeout seconds to call API. Default 3
Example:
xray api adu --server=127.0.0.1:8080  c1.json c2.json
```
```bash
$ ./xray help api rmu
usage: xray api rmu [--server=127.0.0.1:8080] -tag=tag <email1> [email2]...
Remove users from inbounds.
Arguments:
-s, -server
The API server address. Default 127.0.0.1:8080
-t, -timeout
Timeout seconds to call API. Default 3
-tag
Inbound tag
Example:
xray api rmu --server=127.0.0.1:8080 -tag="vless-in" "xray@love.com" ...
``` …
=> Commands: Add adu/rmu inbound user management to API

app/proxyman/inbound/inbound.go, app/proxyman/outbound/outbound.go
rt copy不是多余只是用错了没发挥作用而已 没tag的handler是一个切片但是有的是一个map 所以是copy+遍历
=> app/proxyman/inbound/inbound.go: Fix ListHandlers()

app/stats/online_map.go
=> API: Fix user online map remain 1 after connection dropped

app/dns/dnscommon_test.go, common/common.go, common/crypto/aes.go, common/crypto/auth_test.go, proxy/dokodemo/dokodemo.go, proxy/shadowsocks/config.go, proxy/vmess/aead/encrypt.go, proxy/vmess/encoding/client.go, proxy/vmess/encoding/server.go, transport/internet/kcp/cryptreal.go, transport/internet/reality/reality.go, transport/internet/splithttp/dialer.go
写自己项目的时候用到了类似must2的功能 挺好的 不过看了一下ray里没有用到泛型(如果有泛型可以省略掉断言)
稍微修改了下就没问题了 结果发现项目里并没有大量使用 而是用了很多 must(err) (可能因为懒得断言) 真用must2的时候好像是因为尝试获取一个aead 直接两个if err != nil太麻烦了破防才用的 不过其实核心里有一个封装的直接从key生成aead的函数 顺手全部替换掉了
=> Refine must2 and apply NewAesGcm() to all usage

go.mod, main/commands/all/tls/ping.go
什么都没发生 好像不像前几次那么艰难
扫了一下更新日志 移除了tls ping使用unsafe获取未导出的密钥交换算法 因为现在connectionstate提供了
看有人说实验性GC的事 它不会被包含在内(因为需要构建时GOEXPERIMENT) 而且它不会减少内存占用 一段内存该不该回收在GC开始时就确定了 能降低的CPU占用也有限因为这个算法优化的是回收碎片内存 xray的大头buffer都是new出来的整块内存 而且是有一个pool管理的(
=> Chore: Migrate to Go 1.25

common/buf/buffer.go, transport/internet/splithttp/dialer.go, transport/internet/splithttp/splithttp_test.go
=> 修复 XHTTP Packet write 丢失字节问题

infra/conf/vless.go, proxy/vless/vless.go
https://github.com/XTLS/Xray-core/issues/4994
Implementation for fr.
How it work.
If defaultFlow isn't set than defaultFlow is "" and all core logic work like in previous versions. But, when we set defaultFlow, then if client don't have flow, then will be set flow from defaultFlow. Its optional parameter.
```json
"settings": {
"defaultFlow": "xtls-rprx-vision",
"clients": [
{
"id": "c481e5e7-2796-491d-ac55-00e3c1e0acc3",
"email": "sOoqSgPC2rHuTWRCPLt3"
}
],
"decryption": "none"
}
```
=> VLESS inbound: Add option to set default `flow`

.github/workflows/release-win7.yml, .github/workflows/release.yml, README.md
https://github.com/XTLS/Xray-core/pull/4952#issuecomment-3189847357
主要参数说明来源于
https://github.com/golang/go/blob/6e676ab2b809d46623acb5988248d95d1eb7939c/src/cmd/compile/internal/gc/main.go#L133-L141
https://github.com/golang/go/blob/6e676ab2b809d46623acb5988248d95d1eb7939c/src/cmd/compile/internal/inline/inl.go#L9-L18
https://github.com/golang/go/blob/6e676ab2b809d46623acb5988248d95d1eb7939c/src/cmd/compile/internal/inline/inl.go#L47-L62
`-gcflags="-l=4"` 目前应该是在不改动环境变量不添加 GOEXPERIMENT 下的比默认情况下激进的内联了（连带 non leaf functions），不过不改变内联节点限制，所以主线 common.go 也有不能内联的内容。
`all=-l=4` 连带依赖外部包一起处理（32 位 MIPS 无缘，最多只能 -l=4，不然直接不出货）
=> Build: Use more aggressive inlining for higher efficiency

main/commands/all/convert/protobuf.go
~~这么久了似乎没人发现用 `xray convert pb config.json c1.json c2.json c3.json > mix.pb` 这个方式出来的 proto 文件没法正常用的吗，看来现在用 proto 配置的没几个了~~
用 `xray convert pb config.json c1.json c2.json c3.json > mix.pb` 转换配置文件到 proto 文件的时候，这个操作其实是将控制台输出写到文件（期望的 proto），但是会将读取配置文件产生的 log （写到控制台）也一并写进文件，导致产生的文件不能用。 ~~其实用十六进制编辑器或者什么的把头部的 log 去掉就好，但是依然比较麻烦~~
现增加一个选项 -outpbfile，直接将生成的 proto 直接写到指定文件位置，出来的 proto 文件直接就能用。
比如： `xray convert pb -outpbfile output.pb config.json c1.json c2.json c3.json` 将 config.json c1.json c2.json c3.json 合并后转换成 proto 并直接写入到 output.pb
~~功能描述要不要再调整，调用 `core.LoadConfig` 可以使用 JSON(C) YAML TOML 格式的配置~~
=> Commands: Add `-outpbfile` for `convert pb`

proxy/wireguard/client.go
close #5053 
跟我说的一样wg实现很怪 甚至用 `_ =` 来忽略全部返回值 这个defer整一个就是坏的 h.bind 也很不合适 暂时糊一个上去吧
=> WireGuard outbound: Fix close closed

proxy/dns/dns.go
1. because we don't have `UplinkOnly/DownlinkOnly`, after outbound-connection is closed(`response` returned), `request` function(and as a result inbound-connection) remain open for a long time(especially when the network is TCP)
///
2. we have a weird code in:
https://github.com/XTLS/Xray-core/blob/4064f8dd8080b0e278df79e0a42c0b153b1d445e/proxy/dns/dns.go#L393
it should be: `return 0, err`(dns-query is not sent but we are waiting for a response!)
=> DNS outbound: Fix some issues

transport/internet/kcp/cryptreal.go
改函数的时候复制错了 本来是取32位数组的前16位作为切片的不小心都丢进去了
这样还不会坏test 因为它直接根据切片长度返回具体算法(16字节128 32字节256) 导致导出相同的AEAD函数并且没有break任何东西从而可以正常解密 约等于把KCP加密的AES128GCM换成了AES256GCM 新版本倒新版本都可以联通 只有混用新旧或者用其他实现才会爆炸
=> mKCP: Fix key derivation for obfuscation

app/proxyman/inbound/worker.go
根据透明代理的原理 它是获取localaddr获得得到地址的 如果有程序出于不知道什么目的直连这个端口那它就会无限尝试自己连自己最后一个请求就把核心打oom
找了一圈没找到什么办法判断一个conn是直连还是来自透明代理模块 目前的方法是检查目标地址是否和监听地址相等 对于监听0000的入站 先检查端口是否相同再用系统调用获得全部本地ip检查目标ip是否等于本地ip(先检查port的原因是syscall比较昂贵)
如果有更好的方法欢迎指出 网上大多数透明代理资料甚至还是ray周边的 ~~甚至是我自己写的文档~~
=> TPROXY: Prevent TCP loopback

app/reverse/bridge.go, app/reverse/portal.go, common/mux/client.go, common/mux/server.go, common/mux/session.go, common/mux/session_test.go, proxy/proxy.go
fix problems:
1. after using `DispatchLink`, we may have goroutine-leak when connection between mux-client and mux-server cut.
2. in some cases in mux `dispatchLink` wait on wrong things and it cause code-stuck and goroutine leak.
3. for reverse, we may have goroutine-leak when a sub-client-connection cut
///
4. most NAT TCP translations time out is 24 hours, so change splice-timeout to 24 hours.
=> MUX: Prevent goroutine leak

proxy/vless/outbound/outbound.go
fix #5140 
在使用reverse command的时候会跳过这里对于input的获取导致拿到空指针最后一层层传下去最后空指针崩溃 只要把它和TCP command一起处理即可
顺带加上了遇到未知command直接panic避免未来的此类问题
=> Fix vless reverse panic in vision

common/protocol/headers.go
https://github.com/refraction-networking/utls/pull/371
=> fix: darwin arm64 always has AESGCMHardwareSupport
