- go.mod
- go.sum
- infra/conf/serial/loader.go
- main/distro/all/all.go
- main/run.go
- main/toml/errors.generated.go
- main/toml/toml.go
Using [github.com/BurntSushi/toml](https://github.com/BurntSushi/toml)
resolves #75
> TOML support

- app/dispatcher/default.go
根据此提议加强日志信息 https://github.com/XTLS/Xray-core/discussions/56#discussioncomment-255112
> optimized log

- proxy/trojan/server.go
fix [https://github.com/v2fly/v2ray-core/issues/495](https://github.com/v2fly/v2ray-core/issues/495)
> Do not panic when UDP dispatcher fails to write response

- go.mod
- go.sum
- proxy/trojan/server.go
- proxy/vless/inbound/inbound.go
> Update pires/proxyproto & Fix fallback error when original address is unix socket

- infra/conf/router.go
- transport/internet/http/hub.go
* Routing: consistent with domains key in DNS configuration 
* Fix: http2: listen port failed use error level log
> Changes from v2fly-core

- transport/internet/tls/config.go
- transport/internet/xtls/config.go
> fix OCSP Stapling

- proxy/shadowsocks/server.go
shadowsocks.handlerUDPPayload -> shadowsocks.handleUDPPayload
> Style: Typo Fix

- core/config.go
- core/functions.go
- infra/conf/serial/builder.go
- main/run.go
支持多种格式配置文件(json, yaml, toml)混合，但只能有一个 protobuf 文件。
本地已测试。
> Add support for loading config from different formats.

- proxy/shadowsocks/config.go
- proxy/shadowsocks/protocol.go
- proxy/shadowsocks/protocol_test.go
- proxy/shadowsocks/server.go
- proxy/shadowsocks/validator.go
**Benchmark**
Thanks for @NutterChen 's test  
Sever: Linux AMD64  
Method: iperf3 30 seconds 5 threads
|  commit  |  Sender  | Receiver |
| :--------: | :--------: | :--------: |
| 523c416bb56b3e2ffe101e7c02a323cfa770bfda | 2.00 Gbits/sec | 1.98 Gbits/sec |
| 0e44d1c21444dc528406e3a0e5cdc582699cb775 | 2.20 Gbits/sec | 2.19 Gbits/sec | 
523c416bb56b3e2ffe101e7c02a323cfa770bfda:  
0e44d1c21444dc528406e3a0e5cdc582699cb775:
> Refactor: Add Shadowsocks Validator

- app/proxyman/inbound/inbound.go
- app/proxyman/outbound/outbound.go
> Restrict tags to be unique

- common/platform/others.go
> Add /opt to assets location

- transport/internet/http/dialer.go
> Change: http transport timeout

- .github/workflows/release.yml
删掉了 artifacts 中的 dgst，改为计算所有文件的 hash。 
是否需要加到 release 文件中？
> Chore: Adjust release.yml

- app/dns/dohdns.go
- app/dns/server.go
- transport/internet/system_dialer.go
> Resolve conflicting change in DNS #309 #341

- infra/conf/trojan.go
- infra/conf/vless.go
> fix: fix the TrojanServerConfig Fallback issue

- transport/internet/grpc/encoding/hunkconn.go
- transport/internet/grpc/encoding/multiconn.go
> Add remote addr to grpc transport layer conn

- common/buf/buffer.go
- transport/internet/grpc/encoding/hunkconn.go
- transport/internet/grpc/encoding/multiconn.go
fix https://github.com/XTLS/Xray-core/issues/409
> Fix: grpc multi accepting empty bytes

- main/commands/all/tls/cert.go
> docs: add common name to the help of tls cert

- transport/internet/grpc/dial.go
- transport/internet/http/dialer.go
> Fix: grpc & http/2 dialer

- transport/internet/quic/dialer.go
- transport/internet/quic/hub.go
the same fix with https://github.com/v2fly/v2ray-core/pull/850
> fix QUIC disconnecting issue

- transport/internet/grpc/dial.go
https://github.com/v2fly/v2ray-core/commit/e00d80eac432b4265f8d4929ec45db30a1a41de6
Thanks @xiaokangwang
> cancel failed grpc connection

- infra/conf/router.go
https://github.com/v2fly/v2ray-core/commit/e22cf451f4c18d19a9eb79911c4c4d120ea81b0d
Thanks @xiaokangwang
> Allow bulk definition of domain matcher at parent level

- README.md
Qv2ray is no longer maintained.
> Remove Qv2ray

- common/errors/errorgen/main.go
https://github.com/v2fly/v2ray-core/pull/821
Thanks @Loyalsoldier
> Chore: refine errorgen (#821)

- core/format.go
- core/xray_test.go
- infra/vformat/main.go
https://github.com/v2fly/v2ray-core/pull/802
Thanks @Loyalsoldier
> Feat: format code in one-key (#802)

- proxy/vmess/encoding/server.go
- proxy/vmess/inbound/inbound.go
- proxy/vmess/validator.go
https://github.com/v2fly/v2ray-core/pull/717
Thanks @xiaokangwang
> Deprecate legacy VMess header with a planned decommission

- proxy/shadowsocks/client.go
> Send shadowsocks handshake with payload if available

- main/distro/all/all.go
Thanks QxQ <59914293+U-v-U@users.noreply.github.com>
> grammar fix

- proxy/vmess/encoding/commands.go
- proxy/vmess/encoding/commands_test.go
> Fix DoS attack vulnerability in CommandSwitchAccountFactory

- common/drain/drain.go
- common/drain/drainer.go
- common/drain/errors.generated.go
- proxy/shadowsocks/protocol.go
- proxy/vmess/encoding/client.go
- proxy/vmess/encoding/encoding_test.go
- proxy/vmess/encoding/server.go
- proxy/vmess/outbound/outbound.go
- testing/scenarios/vmess_test.go
> Unified drain support for vmess and shadowsocks

- README.md
doc: add contributing section to readme and update build instruction style
> doc: add contributing section to readme and update build instruction style

- proxy/vmess/encoding/commands.go
https://github.com/v2fly/v2ray-core/pull/1492
> Update Vmess Warning Errors

- .github/workflows/release.yml
As is shown in <https://github.com/XTLS/Xray-core/issues/28> that Xray don't have a program working on the background on Windows. Maybe it's a little bit hard for normal Xray-users to find this issue but it is really essential for some windows user to run Xray without GUI. So I add the 'wxray.exe' into windows release package.
I really appreciate for your working on Xray and I want to provide as much as I can to make Xray better! Thanks!
> Add background-working Xray to windows release version.

- app/dns/nameserver_udp.go
- core/context.go
- core/context_test.go
- core/functions.go
> Fix context api and document

- .github/dependabot.yml
[Relates documentation](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem)
> Maintain dependencies for GitHub Actions

- app/dns/fakedns/fake.go
- app/dns/fakedns/fakedns_test.go
In rare cases different domains asking for dns will return the same IP. Add a mutex.
> Fix a concurrency issue in fakedns

- README.md
I have added a client guide for adapting use xray for macOS, Looking forward to review. @yuhan6665
> Add V2RayXS to the macOS client

- app/dispatcher/default.go
- the code is removed in DNS refactor by mistake
- add another pattern for observatory routing
> Reapply optimized log

- infra/conf/common.go
> fix: read port from environment variable

- app/dispatcher/fakednssniffer.go
v2fly/v2ray-core@1df432218eaa71b8c3ec3de0af9308399a90fd56
> fix fakedns is nil

- proxy/vmess/encoding/client.go
- proxy/vmess/encoding/server.go
- proxy/vmess/inbound/inbound.go
- proxy/vmess/outbound/outbound.go
> Fix DoS attack vulnerability in VMess Option Processing

- transport/internet/udp/hub_freebsd.go
> fix(udp): check addr nil (close 1807)

- transport/internet/quic/dialer.go
- transport/internet/quic/hub.go
Changed quic MaxIdleTimeout from 30s to 5min & HandshakeIdleTimeout to 8s
> Changed quic MaxIdleTimeout time& HandshakeIdleTimeout time

- go.mod
- go.sum
- proxy/shadowsocks_2022/config.go
- proxy/shadowsocks_2022/inbound.go
- proxy/shadowsocks_2022/inbound_multi.go
A first implements proxy.UserManager of shadowsocks2022
Considering implements shadowsocks2022 in xray-core may have better performance when crud users.
#1372
> update: Implement the proxy.UserManager of ss2022

- proxy/vless/encoding/encoding.go
- proxy/vless/outbound/outbound.go
Certain ssh, mySQL and reverse proxy need server data first in a connection
> Fix VLESS client doesn't handle traffic if not send data first

- .github/workflows/release.yml
refactor download *.dat files. I test it on my repo, works normally
> update: release.yml

- common/protocol/headers.go
Same as https://github.com/v2fly/v2ray-core/commit/a8b0991b52b4ea68519a096feb255b5a562152b4
> Refine the logic of security type AUTO

- proxy/trojan/server.go
- proxy/vless/inbound/inbound.go
@yuhan6665 @RPRX 
Fork the code and revise them per the RPRX instruction mentioned in [XTLS#1515](https://github.com/XTLS/Xray-core/issues/1515)  the result is good for over 15 mins in my network environment. Error log is attached. 
You can find the complied files in [here](https://github.com/asiaqa/docker-xray/releases/tag/20230106)
Error Log:
[error-20230117-386.log](https://github.com/XTLS/Xray-core/files/10430683/error-20230117-386.log)
P.S.
After checking the debug logs....I think the problem may be I did customize and add more than 200k reject domain rules and it slows down the processing time. (geosite.dat)
[Debug] app/router: MphDomainMatcher is enabled for 201687 domain rule(s)
> Revise the Code per XTLS#1515

- main/commands/all/x25519.go
For example (Xray main):
```shell
root@brain:~/xray# ./xray x25519 -i 92ufOhzjquGUKbBuMe9h86EY1Xlo72LwgorzbvQKO7s
Private key: 92ufOhzjquGUKbBuMe9h86EY1Xlo72LwgorzbvQKO7s
Public key: Hp3NguOFJISWeTpJvFapRyjjTHH4xM7XF5yOWYE0YWs
root@brain:~/xray# ./xray x25519 -i 8GufOhzjquGUKbBuMe9h86EY1Xlo72LwgorzbvQKO3s
Private key: 8GufOhzjquGUKbBuMe9h86EY1Xlo72LwgorzbvQKO3s
Public key: Hp3NguOFJISWeTpJvFapRyjjTHH4xM7XF5yOWYE0YWs
```
This PR avoids generating equivalent X25519 private keys for Go curve25519 package. This will remove confusion and eliminate potential threats.
> Avoid X25519 private key confusion

- README.md
This pr adds a new way of install xray reality on your machine
> doc: include a new xray reality installation script

- README.md
https://github.com/Misaka-blog/Sing-box-Reality
This is my one-key script, you can look for it
> Update my one-key install script for sing-box Reality

- .github/docker/Dockerfile
- .github/docker/files/config.json
- .github/workflows/docker.yml
> feat : support docker build

- proxy/wireguard/wireguard.go
> Fix memory leak caused by Wireguard outbound

- README.md
This pull request introduces three new graphical user interface (GUI) clients to execute V2Ray project configurations. The GUI clients provide a user-friendly interface for configuring and managing V2Ray settings efficiently.
Changes Made:
Added GUI client NekoRay: [Qt based cross-platform GUI proxy configuration manager (backend: v2ray / sing-box)] (Created by @MatsuriDayo)
Added GUI client B: [v2rayA is a V2Ray Linux client supporting global transparent proxy, compatible with SS, SSR, Trojan(trojan-go), [PingTunnel](https://github.com/esrrhs/pingtunnel) protocols. [[SSR protocol list]](https://github.com/v2rayA/shadowsocksR/blob/feat_v5/README.md#ss-encrypting-algorithm)]
Added GUI client Qv2ray: [Cross-platform V2ray Client written in Qt]
> Add Linux GUI clients

- README.md
Help the author update, his github cleaned up the account to 90 days username to re-use.
> Wings X rename to FoXray

- transport/internet/headers/dns/dns.go
Saves around 0.7MB compiled binary size
> Clean code dependencies on github.com/miekg/dns

- proxy/vless/encoding/encoding.go
- proxy/vless/inbound/inbound.go
- proxy/vless/outbound/outbound.go
fix [https://github.com/XTLS/Xray-core/issues/2238](https://github.com/XTLS/Xray-core/issues/2238)
> XRV should work without rawConn

- README.md
Hi. Thanks for such greate project. I created a cross-platform GUI client based on PySide6 that supports Xray-core and also a python wrapper for this project in my spare time to help spread its influence. If you are kind enough please try using it and see if it meets the basic GUI requirements for this project. Hope I can get their project address shown in the README. Thanks!
> Add more GUI and wrapper link in README.md

- go.mod
- go.sum
- proxy/wireguard/tun.go
> Fix go 1.21 build, see #2466

- transport/internet/sockopt_darwin.go
sockopt->interface now works in darwin ios/macos
```
"streamSettings": {
"sockopt": {
"interface": "en0"
}
},
```
> set sockopt interface for darwin

- infra/conf/xray.go
> Fix typo in xray.go

- README.md
写了半天英文，感觉挺别扭的，还是用中文吧。
因为闭源的缘故，很抱歉给社区带来了负面影响；同时也是由于生活所迫，自己再没有额外的精力维护项目。自此，我提议在README中删除我的项目，并推荐大家使用其他仍在维护的版本。  
原本想说的话有很多，可惜千言万语到此都作烟云顿散。  
相信我不会离开，我们总会以其他的方式再次见面。
> delete my repo for unnecessary disputes

- app/router/balancing.go
issue: https://github.com/XTLS/Xray-core/issues/2898
> fix roundRobin strategy behavior when using api

- common/reflect/marshal.go
- core/config.go
> Remove slices dependency.

- proxy/wireguard/client.go
> fix #2970 parsing IPv6 address in wireguard peers configure

- app/dispatcher/default.go
- proxy/dns/dns.go
> FakeDNS return TTL=1 and drop HTTPS QType 65 request

- app/dns/dns.go
- app/router/command/command_test.go
- common/dice/dice.go
- common/drain/drainer.go
- main/commands/all/api/shared.go
- main/commands/all/tls/certchainhash.go
- proxy/socks/server.go
- testing/scenarios/command_test.go
- testing/scenarios/metrics_test.go
- transport/internet/grpc/dial.go
fix some errors detected by staticcheck
> chore: fix some errors detected by staticcheck

- README.md
- We use github actions to release the Xray API fully automatically as fast as possible
- We can manage many programming languages, now we support `cpp` and `python`
> Add a new xray wrapper

- main/commands/all/api/balancer_info.go
> Improve balancer_info API

- transport/internet/config.go
- transport/internet/httpupgrade/config.go
> Fix HTTPUpgrade init

- .github/workflows/release.yml
- Makefile
Makefile: remove unneccesary `install` target &
Add build to `.PHONY` target
> CI: not create zip file when not releasing

- app/dispatcher/default.go
> Add regex support for domainsExcluded

- transport/internet/websocket/dialer.html
On my machine, browserdialer speedtest gives 10 Mbit/s download. Now it can do 300 Mbit/s.
> Make browserdialer faster

- transport/internet/http/config.go
- transport/internet/httpupgrade/hub.go
- transport/internet/internet.go
- transport/internet/splithttp/hub.go
- transport/internet/websocket/hub.go
Also fix H2 transport to not verify if host is not defined
> Properly parse HTTP host for verification

- .github/ISSUE_TEMPLATE/config.yml
> Add link to GitHub discussions

- proxy/freedom/freedom.go
https://github.com/XTLS/Xray-core/issues/3529
> Don't do raw/splice copy in case of MITM

- proxy/wireguard/client.go
https://github.com/2dust/v2rayNG/issues/3359
bug was introduced when refactor log
> Fix a nil pointer in Wireguard client logging

- README.md
add new xray-core panel on Readme file
> Readme: add Marzneshin panel

- transport/internet/browser_dialer/dialer.html
https://github.com/XTLS/Xray-core/issues/3882#issuecomment-2396167708
This does not fix the linked issue (and I can't repro the issue there anyway), just a random bug I found.
> Browser Dialer: Revert changes to event listeners

- common/common.go
- infra/vformat/main.go
- infra/vprotogen/main.go
- main/commands/all/api/shared.go
use errors.New to replace fmt.Errorf with no parameters
> chore: use errors.New to replace fmt.Errorf with no parameters

- README.md
> README.md: Add xray-checker to Xray Tools

- main/commands/all/api/balancer_info.go
- main/commands/all/api/balancer_override.go
- main/commands/all/api/inbound_user.go
- main/commands/all/api/inbound_user_count.go
- main/commands/all/api/inbounds_add.go
- main/commands/all/api/inbounds_remove.go
- main/commands/all/api/logger_restart.go
- main/commands/all/api/outbounds_add.go
- main/commands/all/api/outbounds_remove.go
- main/commands/all/api/rules_add.go
- main/commands/all/api/rules_remove.go
- main/commands/all/api/source_ip_block.go
- main/commands/all/api/stats_get.go
- main/commands/all/api/stats_online.go
- main/commands/all/api/stats_online_ip_list.go
- main/commands/all/api/stats_query.go
- main/commands/all/api/stats_sys.go
Hi,
I updated various command descriptions and usage lines in the API commands to improve clarity and consistency.
> API: Improve cli usage descriptions

- README.md
add new xray-core client on Readme file
> README.md: Add Happ to iOS clients

- app/dns/nameserver.go
from 192 168 0 1 to 192.168.0.1
> DNS log: Optimize IP address display

- .github/workflows/release.yml
使用NDK编译安卓的Xray，使net.LookupIP可以正常解析域名
https://github.com/go-cross/cgo-actions
> Workflows: Build Android(7+) using NDK; Add Android(7+) amd64 build

- app/dns/nameserver.go
- go.mod
- go.sum
- transport/internet/sockopt_linux.go
Standard formatting and removal of redundant structures
Update gvisor associated with go version
Hi I didn't make any changes to the Go version and gvisor was upgraded to the latest version.
@RPRX
> Chore: Update gVisor to the latest version; Fmt .go files

- .github/workflows/release-win7.yml
- .github/workflows/scheduled-assets-update.yml
Authenticating the GitHub API call with GitHub token to avoid [the ratelimte](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users). Referenced documentation: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
Tested in my fork: https://github.com/yin1999/Xray-core/actions/runs/14859797633/job/41721569355
> Workflows: Authenticating the GitHub API call with GitHub token

- README.md
> README.md: Add Amnezia VPN to Others

- testing/scenarios/command_test.go
Fix PR#4723 Test
测试代码有问题，Github CI环境高概率报错
> Tests: Fix TestCommanderListHandlers

- infra/conf/transport_internet.go
- infra/conf/trojan.go
- infra/conf/vless.go
- infra/conf/vless_test.go
Fix https://github.com/XTLS/Xray-examples/issues/234
> VLESS fallbacks: `dest` defaults to "127.0.0.1" -> "localhost"

- proxy/dns/dns.go
https://github.com/XTLS/Xray-core/pull/4824#issuecomment-3078811352
这里不应该 common.Must 因为收到的是外来数据
> DNS: Prevent panic from rejecting invalid domain

- README.md
add new xray-core client on Readme file
> README.md: Add Happ to macOS x64 & tvOS Clients

- infra/conf/transport_internet.go
> REALITY config: Allow `mldsa65` fields to be empty

- app/dns/dns.go
> checkSystemNetwork(): Use c.root-servers.net

- app/dns/dnscommon_test.go
> Test_parseResponse(t *testing.T): Use dns.google for IPv6

- app/reverse/portal.go
- common/mux/client.go
https://github.com/XTLS/Xray-core/issues/5088#issuecomment-3263558403
> app/reverse/portal.go: Fix goroutine leak & Add EndpointOverride

- app/reverse/bridge.go
https://github.com/XTLS/Xray-core/pull/5101#issuecomment-3273320244
> app/reverse/bridge.go: Add timer nil check
